scalar Upload
scalar ObjectId
scalar Date


type Mutation {
   createWarrantyClaimRequestByUSer(input:createWarrantyClaimRequestByUSerInput! 
   image: [Upload]):createWarrantyClaimRequestByUSerResponse

   createWarrantyClaimRequestByUSerInMobile(input:createWarrantyClaimRequestByUSerInput! 
   image: [Upload]):createWarrantyClaimRequestByUSerResponse



   updateClaimStatusByAdmin(input:updateClaimStatusByAdminInput!):updateClaimStatusByAdminResponse
   updateClaimStatusByAdminAgentStatus(input:updateClaimStatusByAdminAgentStatusInput!):updateClaimStatusByAdminAgentStatusResponse
   claimOtpVerificationByAdminAGentStatus(input:claimOtpVerificationByAdminAGentStatusInput):claimOtpVerificationByAdminAGentStatusResponse
}

type Query {
    getAllClaimRequestsByAdmin(input:getAllClaimRequestsByAdminInput):getAllClaimRequestsByAdminResponse
    getClaimRequestDetailsByAdmin(input:getClaimRequestDetailsByAdminInput!):getClaimRequestDetailsByAdminResponse
    getWarrantyActivityLogByAdmin(input:getWarrantyActivityLogByAdminInput!):[getWarrantyActivityLogByAdminResponse]
    getOrderProductWarrantyClaim(input:getOrderProductWarrantyClaimInput):getOrderProductWarrantyClaimResponse
}



input claimOtpVerificationByAdminAGentStatusInput{

      claimRequestId: ObjectId!
    code: String!
    claimStatus: String
    remarks: String
    agentId:ObjectId
    
}

type claimOtpVerificationByAdminAGentStatusResponse{

       status: Boolean
   msg: String
}


type updateClaimStatusByAdminAgentStatusResponse{

       status: Boolean
    otp: Boolean
    msg: String
}




input updateClaimStatusByAdminAgentStatusInput{

     claimRequestId:ObjectId!
   claimStatus:String!
   remarks:String
   agentId:ObjectId
}

type getOrderProductWarrantyClaimResponse{

      _id: ObjectId
  claimStatus: String
}


input getOrderProductWarrantyClaimInput{

     orderProductId:ObjectId
}

type getOrderProductWarrantyClaimResponse{

    _id:ObjectId,
    claimStatus:String
}




 input getWarrantyActivityLogByAdminInput{

          warrantyId:ObjectId
 }




type performedByType{

  _id:ObjectId
  name:String
}


type getWarrantyActivityLogByAdminResponse{

        _id:ObjectId
  actionType: String
  action: String
  performedBy: ObjectId
  performedByRole: String
  referenceId: ObjectId
  referenceType: String
  details:String
  createdAt:Date
  timeDifference:Int
  performedByDetails:[performedBy]
}



input warrantyAddressInput{
  firstname: String
  email: String
  mobile: String
#   streetName: String
#   city: String
#   houseNumber: String
  country: String
  postCode: String
#   apartment: String
#   suite: String
#   unit: String
  governorate: String!
  village: String!
  governorateID: String!
  villageID: String!
  address:String
}

input createWarrantyClaimRequestByUSerInput{
    productId:ObjectId!
    claimType:String!
    issueDescription:String
    warrantyAddress:warrantyAddressInput!
}

input getAllClaimRequestsByAdminInput{
    page:Int
    size:Int
    search:String
    claimStatus:String
}

input getClaimRequestDetailsByAdminInput{
    claimRequestId:ObjectId!
}

input updateClaimStatusByAdminInput{
     claimRequestId:ObjectId!
     claimStatus:String!
     agentStatus:Boolean
     Reason:String
     Date:Date
}

type claimUserDetail{
    _id:ObjectId
    displayName:String
}

type warranty{
    name:String
    description:String
    duration:Int
    warrantyType:[String]
}

type claimProductDetail{
    productId:String
    warranty:warranty
    productName:String
    deliveryDate:Date
    shippingStatus:String
    orderDate:Date
    paymentStatus:String
    shippingCharge:Float
    sellingPrice:Float
    shortDescription:String
    paymentMode:String
    vendorId:ObjectId
    itemId:String
    courierId:String
    invoiceNumber:String
    warehouseSkuId:String
}

type claimVendorDetail{
  fullName:String
}

type claimAgentDetail{
   contactNumber:String,
   agentType:String,
}

type claimProductsDetail{
  images:[FileData]
}

type warrantyAddress{
  firstname: String
  email: String
  mobile: String
#   streetName: String
#   city: String
#   houseNumber: String
  country: String
  postCode: String
#   apartment: String
#   suite: String
#   unit: String
  governorate: String!
  village: String!
  governorateID: String!
  villageID: String!
  address:String
}


type getClaimRequestDetailsByAdminResponse{
    user:claimUserDetail
    product:claimProductDetail
    vendor:claimVendorDetail
    products:claimProductsDetail
    agent:claimAgentDetail
    _id:ObjectId
    createdAt: Date
    issueDescription: String
    order:String
    warrantyId:String
    claimStatus:String
    claimType:String
    claimDate:Date
    rejectedReason:String
    rejectedDate:Date
    productImage:[FileData]
    warrantyAddress:warrantyAddress
    replacementDate:Date,
    replacementReason:String,
    replacementShippedDate:Date,
    replacementCompletedDate:Date,
    returnedWarehouseDate:Date,
    postponedDate:Date,
    postponedReason:String,
    deliveryAgentId:ObjectId,
    deliveryAgentName:String,
    deliveryAgentAssignedOn:Date,
    productImageUploadByAgent:[FileData],
}


type createWarrantyClaimRequestByUSerResponse{
   success: Boolean
   message: String
}

type updateClaimStatusByAdminResponse{
   success: Boolean
   message: String
}


type claimUser{
    displayName:String
}

type claimProduct{
    productName:String
    _id:ObjectId
    itemId:String
}

type claimData{
    user:claimUser 
    product: claimProduct
    _id:ObjectId
    productImage:[FileData]
    createdAt: Date
    issueDescription: String
    order:String
    warrantyId:String
    claimStatus:String
    claimType:String
}

type getAllClaimRequestsByAdminResponse{
    success: Boolean
    data: [claimData]
    maxRecords: Int
}


# Schema

schema {
  mutation: Mutation
  query: Query
}
