scalar Upload
scalar ObjectId
scalar Date


type Mutation {
   createWarrantyClaimRequestByUSer(input:createWarrantyClaimRequestByUSerInput! 
   image: [Upload]):createWarrantyClaimRequestByUSerResponse
}

type Query {
    getAllClaimRequestsByAdmin(input:getAllClaimRequestsByAdminInput):getAllClaimRequestsByAdminResponse
}

input warrantyAddressInput{
  firstname: String
  email: String
  mobile: String
#   streetName: String
#   city: String
#   houseNumber: String
  country: String
  postCode: String
#   apartment: String
#   suite: String
#   unit: String
  governorate: String!
  village: String!
  governorateID: String!
  villageID: String!
  address:String
}

input createWarrantyClaimRequestByUSerInput{
    productId:ObjectId!
    claimType:String!
    issueDescription:String
    warrantyAddress:warrantyAddressInput!
}

input getAllClaimRequestsByAdminInput{
    page:Int
    size:Int
    search:String
}


type createWarrantyClaimRequestByUSerResponse{
   success: Boolean,
   message: String,
}

type claimUser{
    displayName:String
}

type claimProduct{
    productName:String
}

type claimData{
    user:claimUser , 
    product: claimProduct, 
    createdAt: Date,   
    issueDescription: String,
    order:String,
    warrantyId:String,
    claimStatus:String,
    claimType:String
}

type getAllClaimRequestsByAdminResponse{
    success: Boolean,
    data: [claimData],
    maxRecords: Int
}


# Schema

schema {
  mutation: Mutation
  query: Query
}
