  scalar Upload


# Cms Mutations


  type Mutation {
    createCategory(input: CreateCategoryInput!, image:Upload): CreateCategoryResponse!
    updateCategory(input: UpdateCategoryInput!, image:Upload): UpdateCategoryResponse!
    deleteCategory(input: CategoryId!): DeleteCategoryResponse!
  }

    # Input

    input CreateCategoryInput {
        categoryName: String!
        parentId: String
        isBlocked: Boolean
        description: String
        isLeaf: Boolean
        attributes: [String]
    }

    input UpdateCategoryInput {
        _id: String!
        categoryName: String
        parentId: String
        isBlocked: Boolean
        description: String
        isLeaf: Boolean
        attributes: [String]
        # brands: [String]
    }

    input CategoryId {
        _id: String!
    }

    input CategoryRecordIdInput {
        _id: String
    }

    # Output

    type CreateCategoryResponse {
        _id: String!
    }

    type UpdateCategoryResponse {
        _id: String!
        message: String
    }

    type DeleteCategoryResponse {
       _id: String!
       message: String
    }

    type CategoryRecordId {
        _id: String
    }


# Cms Queries

 type Query {
  getAllChildCategories(input:GetAllChildLevelCategoriesInput!): GetAllChildLevelCategoriesResponse!
  getActiveChildCategories(input:GetActiveChildCategoriesInput!): GetActiveChildCategoriesResponse!
  getActiveChildCategoriesInMobile(input:GetActiveChildCategoriesInMobileInput!): GetActiveChildCategoriesInMobileResponse!
  getActiveCategoryTree: getActiveCategoryTreeResponse!
  getActiveCategoryTreeInMobile: getActiveCategoryTreeInMobileesponse!
  getCategoriesAutoComplete(input:GetCategoriesAutoCompleteInput!):GetCategoriesAutoCompleteRespons
  getAllLeafRecords: getAllLeafRecordsResponse!
  getLevelCategories(input:GetLevelCategoriesInput): GetLevelCategoriesResponse!
  getAllCategoriesOfVendor: getAllCategoriesOfVendorResponse!
  getAllCategoriesOfVendorByAdmin(input:vendorIdInput!): getAllCategoriesOfVendorResponse!
  getCategoriesByAdminForCoupon(input:categoryForCouponInput!): CategoriesForCouponResponse!
}   

    # Input
     input GetAllChildLevelCategoriesInput{
      parent:String
    }

    input GetActiveChildCategoriesInput{ 
      parent:String
    }

    input GetActiveChildCategoriesInMobileInput{ 
      parent:String
    }
  

    input GetCategoriesAutoCompleteInput{
      query:String!
    }

    input GetLevelCategoriesInput{
      level: Int
      limit: Int
    }

    input vendorIdInput {
      vendorId: String!
    }
    input categoryForCouponInput{
      brands:[String]
    }


    # Output

     type ImageData {
      fileType: String
      fileURL: String
      mimeType: String
      originalName: String
    }  

    type Category{
      categoryName:String
      _id: String
      isBlocked: Boolean
      fullCategoryName: String
      isLeaf: Boolean
      description: String
      categoryImage: ImageData
    }

    type CategoryAssignedToVendor{
      categoryName:String
      _id: String
      isBlocked: Boolean
      fullCategoryName: String
      isLeaf: Boolean
    }

    type CategoryNode{
      categoryName:String
      _id: String
      categoryImage: ImageData
      children: [CategoryNode]
      isLeaf: Boolean
    }

    type GetActiveChildCategoriesResponse{
      records:[Category]
    }

    type GetActiveChildCategoriesInMobileResponse{
      records:[Category]
    }

    type GetAllChildLevelCategoriesResponse{
      records:[Category]
    }


    type getActiveCategoryTreeResponse{
      records:[CategoryNode]
    }

    type getActiveCategoryTreeInMobileesponse{
      records:[CategoryNode]
    }

    type CategorySuggestion {
      _id:String!
      description: String!
    }

    type GetCategoriesAutoCompleteRespons {
       suggestions: [CategorySuggestion]
    }

    type getAllLeafRecordsResponse{
      records:[Category]
    }

    type getAllCategoriesOfVendorResponse{
      records:[CategoryAssignedToVendor]
    }
   type CategoryRecord {
    _id: String
    categoryName: String
    
  } 
      type CategoriesForCouponResponse {
      records: [CategoryRecord]
    }


    type GetLevelCategoriesResponse{
      records:[Category]
    }

# Schema

schema {
    mutation: Mutation,
    query:Query
}

