

# Product Mutations

  scalar JSONObject
  scalar Upload
  scalar ObjectId

  type File {
    filename: String!
    mimetype: String!
    encoding: String!
  }

  type Mutation {
    # uploadProductFile(file: Upload!): File
    createProduct(input: ProductInput!, images:[Upload], productDetailImages:[Upload]): ProductResponse
    createVariant(input: VariantInput!, images:[Upload], productDetailImages:[Upload]): VariantResponse
    updateProduct(input: ProductUpdateInput!, images: [Upload], productDetailImages:[Upload]): ProductUpdateResponse
    updateProductByAdmin(input: UpdateProductByAdminInput!, images: [Upload], productDetailImages:[Upload]): UpdateProductByAdminResponse!
    # deleteProduct(input: ProductId!): DeleteProductResponse!
    submitProductForPreviewByVendor(input: ProductPreviewInput!): ProductStatusResponse
  }


    # Input

    input ProductFileDataInput {
    fileType: String
    fileURL: String
    mimeType: String
    originalName: String
    }

    input ProductStatusInput{
      _id: String!
      status: String
      remarks: [String]
    }

    input ProductPreviewInput{
      _id: String!
    }

    input ProductFileDataInput {
        fileType: String
        fileURL: String
        mimeType: String
        originalName: String
    }

   input ProductInput {
    brandId: ObjectId!
    brandName: String!
    productName: String!
    shortDescription: String!
    skuId: String!
    description: String!
    productInfo: [String]
    productShortInfo: String
    rating: Float!
    tags: String!
    sellingPrice: Float!
    price: Float!
    mrp: Float!
    stock: Int!
    categoryId: ObjectId!
    offerPrice: Float
    attributes: [String]
}

input VariantInput {
    productName: String!
    shortDescription: String!
    skuId: String!
    description: String!
    productInfo: [String!]!
    productShortInfo: String
    rating: Float!
    tags: String
    sellingPrice: Float!
    price: Float!
    mrp: Float!
    productCode: Int!
    stock: Int!
    attributes: [String!]!
}

input ProductUpdateInput {
    _id: ObjectId!
    brandId: ObjectId
    brandName: String
    productName: String
    shortDescription: String
    skuId: String
    description: String
    productInfo: [String]
    productShortInfo: String
    rating: Float
    tags: String
    sellingPrice: Float
    price: Float
    mrp: Float
    productCode: Int
    stock: Int
    categoryId: String
    offerPrice: Float
    attributes: [String]
    remarks: [String]

}

input UpdateProductByAdminInput {
    _id: ObjectId!
    brandId: ObjectId
    brandName: String
    productName: String
    shortDescription: String
    skuId: String
    description: String
    productInfo: [String]
    productShortInfo: String
    rating: Float
    tags: String
    sellingPrice: Float
    price: Float
    mrp: Float
    productCode: Int
    stock: Int
    categoryId: String
    status: String
    offerPrice: Float
    attributes: [String]
    remarks: [String]
    isBlocked: Boolean
    warehouseSkuId: String
}

input ProductId {
        _id: String!
 }

    # Output



# Auth Queries

type Query {
    getProductsByAdmin(input:ProductFilters):ProductsResponse!
    getProductsByVendor(input:ProductByVendorFilters):ProductsResponse!
    getProductByAdmin(input: ProductId!): ProductResponse!
    getProductByVendor(input: ProductId!): ProductResponse!
    getVariantsByAdmin(input:VariantsByAdminInput!) : VariantsByAdminResponse!
    getProducts(input:ProductFilters):ProductsResponse!
    getProduct(input: ProductId!): ProductResponse!
    getVariants(input:VariantsInput!) : VariantsResponse!
    getVariantsInMobile(input:VariantsInMobileInput!) : VariantsInMobileResponse!
    getProductsAutoComplete(input:GetProductsAutoCompleteInput!) : GetProductsAutoCompleteResponse
    getRelatedProducts(input: RelatedProductsFilters!):RelatedProductsResponse!
    getVariantsTableByAdmin(input:ProductVariantsByAdminFilter!) : VariantsTableByAdminResponse!
    getVariantsTableByVendor(input:ProductVariantsByVendorFilter!) : VariantsTableByVendorResponse!
    getProductsMaxPrice(input:categoriesInput) : getProductsMaxPriceResponse!

 # MOBILE SIDE APIS
    getProductsInMobile(input:ProductsInMobileFilters):ProductsInMobileResponse!
    getProductInMobile(input: ProductIdInMobile!): ProductInMobileResponse!
    getVariantsInMobile(input:VariantsInMobileInput!) : VariantsInMobileResponse!

}

    # Input
    input ProductFilters {
        page: Int
        size: Int
        tags: [String]
        minPrice: Float
        maxPrice: Float
        newest: Boolean
        priceLowToHigh: Boolean
        priceHighToLow: Boolean
        query: String
        categories:[String]
        parentCategory:String
        brands:[String]
        attributes: [AttributeInput]
        discount: Int
        bestSeller: Boolean
        status: String
        vendorId:ObjectId
    }

    input AttributeInput {
        id: String
        values: [String]
    }

      input ProductsInMobileFilters {
        page: Int
        size: Int
        minPrice: Float
        maxPrice: Float
        newest: Boolean
        priceLowToHigh: Boolean
        priceHighToLow: Boolean
        query: String
        categories:[String]
        parentCategory:String
        brands:[String]
        attributes: [AttributeInput]
        discount: Int
        bestSeller: Boolean
    }

    input ProductByVendorFilters {
        page: Int
        size: Int
        minPrice: Float
        maxPrice: Float
        newest: Boolean
        priceLowToHigh: Boolean
        priceHighToLow: Boolean
        query: String
        categories:[String]
        parentCategory:String
        status: String
    }

    input ProductId {
        _id: String!
    }

    input ProductIdInMobile {
        _id: String!
    }

    input VariantsInput {
        _id: String!
    }

    input VariantsInMobileInput {
        _id: String!
    }

    input VariantsByAdminInput {
        _id: String!
        page: Int
        size: Int
    }

    input GetProductsAutoCompleteInput {
        query: String!
    }

    type DeleteProductResponse {
       _id: String!
       message: String
    }
    
    input RelatedProductsFilters {
        _id: String!
        limit: Int
    }

    input ProductVariantsByAdminFilter {
        productCode: Int!
  }

      input ProductVariantsByVendorFilter {
        # _id: String!
        productCode: Int!
  }

    input categoriesInput {
      categories:[String]
    }


    # Output

    type ProductFileData {
        fileType: String
        fileURL: String
        mimeType: String
        originalName: String
    }

    type Product {
        _id:String
        vendorId: String
        brandId: String
        brandName: String
        productName: String
        shortDescription: String
        skuId: String
        description: String
        productInfo: [String]
        productShortInfo: String
        images: [ProductFileData]
        rating: Float
        sellingPrice: Float
        price: Float
        mrp: Float
        tags: [String]
        productCode: Int
        categoryId: String
        categoryNamePath: String
        categoryIdPath: String
        isBlocked: Boolean
        stock: Int
        status: String
        offerPrice: Float
        attributes: [IProductAttribute]
        productDetailImages: [ProductFileData]
        warehouseSkuId: String
    }

    type IProductAttribute {
        attributeId: String
        attributeName: String
        attributeValueId: String
        attributeValue: String
        attributeDescription: String
   }

    type Attributes {
        # attributeValueId: String
        attributeValue: String
    }

    
    type ProductsResponse {
        maxRecords: Int!
        records: [Product!]
    }

    type ProductsInMobileResponse {
        maxRecords: Int!
        records: [Product!]
    }

    type ProductResponse {
        product: Product!
        message: String
    }

    type ProductInMobileResponse {
        product: Product!
        message: String
    }

    type VariantResponse {
        product: Product!
        message: String
    }

    type ProductUpdateResponse {
        _id: String!
        message: String
    }
    
    type UpdateProductByAdminResponse {
        _id: String!
        message: String
    }
    


    type Variant {
        _id: String!
        productId: String
        attributeId: String
        attributeName: String,
        attributeType: String,
        attributeValueId: String
        attributeValue: String
        attributeDescription: String
        colorCode: String
    }

    type VariantsResponse {
       variants: [Variant]
    }

    type VariantsInMobileResponse {
       variants: [Variant]
    }
    
    type VariantTableByAdmin {
       _id: String
       productName: String
       images: [ProductFileData]
       attributes: [IProductAttribute]
       stock: Int
       status: String
       isBlocked: Boolean
       categoryNamePath: String,
       categoryId: ObjectId,
       warehouseSkuId: String,
       skuId: String,
       productCode: String
       brandName: String
       brandId: ObjectId
    }

    type VariantsByAdmin {
       _id: String
       productName: String
       images: [ProductFileData]
       attributes: [IProductAttribute]
       stock: Int
       status: String
       isBlocked: Boolean
    }

    type VariantTableByVendor {
       _id: String
       productName: String
       images: [ProductFileData]
       attributes: [IProductAttribute]
       stock: Int
       status: String
       isBlocked: Boolean
       productCode: Int
       categoryNamePath: String
       brandId: ObjectId
       brandName: String
       skuId: String
       warehouseSkuId: String
       categoryId: ObjectId
    }

    type VariantsTableByAdminResponse {
       maxRecords: Int!
       records: [VariantTableByAdmin]
       message: String
    }

     type VariantsTableByVendorResponse {
       maxRecords: Int!
       records: [VariantTableByVendor]
       message: String
    }

    type ProductSuggestion {
      suggestion:String!
      image: String
      categoryId: ObjectId
      categoryIdPath: String
    }

    type GetProductsAutoCompleteResponse {
       suggestions: [ProductSuggestion]
    }

    type RelatedProductsResponse {
        records: [Product!]
    }

    type ProductStatusResponse {
        _id: String
        message: String
    }

    type VariantsByAdminResponse {
       maxRecords: Int!
       records: [VariantsByAdmin]
       message: String
    }

    type getProductsMaxPriceResponse {
        maxPrice: Int
        message: String
    }

    

# Schema

schema {
    mutation: Mutation
    query:Query
}

