

# Color Mutations


  type Mutation {
    addColor(input: AddColorInput!): AddColorResponse!
    updateColor(input: updateColorInput!): updateColorResponse!
  }


    # Input

    input AddColorInput {
        categoryId:String!
        colorName: String!
        colorCode: String!
        isBlocked: Boolean
    }   

    input updateColorInput {
         _id: String!
        colorName: String
        colorCode: String
        # isBlocked: Boolean
    }

    # Output

    type AddColorResponse {
        _id: String!
    }  

    type updateColorResponse {
        _id: String!
        message: String
    }


# Color Queries

  type Query {
    getColorRecord(input: colorId!): ColorRecordResponse!
    getActiveColors(input: GetActiveColorsInput):ActiveColorResponse!
    getAllColorsWithCategoryId(input: CategoryIdInput):getAllColorsWithCategoryIdResponse!
  }   

    # Input
   
  input colorId {
    _id: String!
  }

  input GetActiveColorsInput {
    categoryId: String
  }

  input CategoryIdInput {
    categoryId: String
  }

    # Output

  type ColorRecord {
    _id: String
    colorName: String
    colorCode: String
    isBlocked: Boolean
    categoryIdPath: String 
  }  
  
  type ColorRecordResponse {
    record: ColorRecord!
  }

  type ActiveColorResponse{
    records: [ColorRecord]
  }

   type getAllColorsWithCategoryIdResponse{
    records: [ColorRecord]
  }
    


# Schema

schema {
    mutation: Mutation,
    query:Query
}

