scalar ObjectId
scalar Upload


type Mutation {
  # createCouponsByAdmin(input:createCouponsByAdminInput!):CreateCouponsByAdminResponse!
   adminSuspendTheCupone(input:adminSuspendTheCuponeInput!):adminSuspendTheCuponeResponse!
   adminDeleteTheCoupon(input:adminDeleteTheCouponInput!):adminDeleteTheCouponResponse!
   createCouponsByAdmin(input:CreateCouponsByAdminInput!):CreateCouponsByAdminResponse
  #  adminSuspendTheCupone(input:adminSuspendTheCuponeInput):adminSuspendTheCuponeResponse!
   editCouponsByAdmin(input:EditCouponsByAdminInput!):CreateCouponsByAdminResponse
   applyCouponByUser(input:applyCouponByUserInput!):ApplyCouponsByAdminResponse!
   applyCouponByUserInMobile(input:applyCouponByUserInput!):ApplyCouponsByAdminResponse!
   removeCoupon:removeCouponResponse!
   removeCouponInMobile:removeCouponResponse!
}



type Query{
      getAllCoupenToAdmin(input:getAllCoupenToAdminInput!):getAllCoupenToAdminResponse!
      getCouponsByUser:[Coupon]!
      getCouponsByUserMobile:[Coupon]!
      getOneCouponDetails(input:getOneCouponDetailsInput):getOneCouponDetailsRespons!


}



input getOneCouponDetailsInput{

     _id:ObjectId!
}

input removeCouponInput{
    couponId:ObjectId
    code:String
}

type removeCouponResponse{
  success:Boolean
  message:String
}

type getOneCouponDetailsRespons{

   _id: ID
  name: String
  code: String
  description: String
  discountType: String
  discountValue: Int
  max_discount: Int
  minOrderAmount: Int
  usageLimit: Int
  orderCount: Int
  usagePerUserLimit: Int
  startDate: String
  expiryDate: String
  isActive: Boolean
  userDetailsArrya:[userDetailsArrayTypeNew]
  productDetailsArrya:[productDetailsArryaType]
  categoriesDetailsArrya:[categoriesDetailsArryaType]
  brandDeatailsArrya:[brandDeatailsArryaType]
 

}


 type userDetailsArrayTypeNew{

     _id:ObjectId
     firstName:String

 }

 type productDetailsArryaType{

     _id:ObjectId
     productName:String

 }

 type categoriesDetailsArryaType{

     _id:ObjectId
     categoryName:String

 }

 type brandDeatailsArryaType{

      _id:ObjectId
      brandName:String


 }




input getCouponsByUserInput{

     userId:ObjectId
}







input Categoryvalid {
  category: ObjectId
}



type CategoryvalidType {
  category: ObjectId
}

input Productvalid {
  product: ObjectId
}

type ProductvalidType {
  product: ObjectId
}

input Uservalid {
  user: ObjectId
}

type UservalidType {
  user: ObjectId
}

input Brandvalid{
  brand:ObjectId
}

type BrandvalidType{
  brand:ObjectId
}

input adminDeleteTheCouponInput{ 

       _id:ObjectId
}

type adminDeleteTheCouponResponse{

     status:Boolean,
     msg:String
}


input CreateCouponsByAdminInput{
    name:String!
    code:String!
    description:String
    # couponType: String!
    orderCount:Int
    discountType: String!
    couponApplicableType: String
    discountValue: Float
    max_discount: Float
    minOrderAmount: Float
    validCategories: [Categoryvalid]
    validProducts: [Productvalid]
    validUsers: [Uservalid]
    validBrands: [Brandvalid]
    usageLimit: Int
    usagePerUserLimit: Int
    startDate: Date
    expiryDate: Date
}

input EditCouponsByAdminInput{
    _id:ObjectId!
    name:String
    code:String
    description:String
    # couponType: String!
    orderCount:Int
    discountType: String
    couponApplicableType: String
    discountValue: Float
    max_discount: Float
    minOrderAmount: Float
    validCategories: [Categoryvalid]
    validProducts: [Productvalid]
    validUsers: [Uservalid]
    validBrands: [Brandvalid]
    usageLimit: Int
    usagePerUserLimit: Int
    startDate: Date
    expiryDate: Date
}

input applyCouponByUserInput{
  couponId:ObjectId
  code:String
}

type CreateCouponsByAdminResponse{
    success:Boolean
    message:String
}


type ApplyCouponsByAdminResponse{
  success:Boolean
  message:String
}



input adminSuspendTheCuponeInput{

     _id:ObjectId,
     isActive:Boolean
}

type adminSuspendTheCuponeResponse{

      status:Boolean,
      msg:String
}


type getAllCoupenToAdminResponse{

      records: [Coupon ],
     maxRecords: Int
}

input getAllCoupenToAdminInput{

    page:Int
    size:Int
    isActive:String
    startDate:Date
    expiryDate:Date
    search:String


}


type Coupon{
      _id:ObjectId
      name:String
    code:String
    description:String
    # couponType: String!
    orderCount:Int
    discountType: String
    couponApplicableType: String
    discountValue: Float
    max_discount: Float
    minOrderAmount: Float
    validCategories: [CategoryvalidType]
    validProducts: [ProductvalidType]
    validUsers: [UservalidType]
    validBrands: [BrandvalidType]
    usageLimit: Int
    usagePerUserLimit: Int
    startDate: Date
    expiryDate: Date
    isActive:Boolean
}


type ValidCategory {
 
 catogory:ObjectId
 
}

type ValidProduct {
    products:ObjectId
}

type ValidUser {
   
    user:ObjectId
}

type UserUsageLimit {
  userId: ObjectId
  usageCount: Int
}


schema {
  mutation: Mutation
  query: Query
}
