scalar Upload
scalar JSONObject

# attribute  Mutations

type Mutation {
  createAttributeValue(input: CreateAttributeValueInput!): CreateAttributeResponse!
  editAttribute(input: AttributeValueEditInput!): AttributeEditResponse!
}


# attribute  Type

type AttributeValue {
  _id: String
  attributeId: String
  value: String
  colorCode: String
  priority: Int
  isBlocked: Boolean
}


# attribute  Input

input CreateAttributeValueInput {
  attributeId: String!
  value: String!
  colorCode: String!
  priority: Int!
  isBlocked: Boolean
} 


input AttributeValueEditInput {
  attributeId: String
  value: String
  colorCode: String
  priority: Int
  isBlocked: Boolean
}


# attribute  Output

type CreateAttributeValueResponse {
  _id: String
  message: String
}

type AttributeValueEditResponse {
  attributeId: String
  value: String
  colorCode: String
  priority: Int
  isBlocked: Boolean
  message: String
}

input AttributeValueRecordsByAdminFilter {
 page: Int,
 size: Int,
 isBlocked: Boolean
}

type AttributeValueRecordsByAdminResponse {
    maxRecords: Int!
    records: [Attribute!]
}

type Query {
  getAllAttributeValueRecordsByAdmin(input: AttributeValueRecordsByAdminFilter): AttributeValueRecordsByAdminResponse!
  # getAttributeRecordByVendor(input:  AttributeRecordByAdminInput!): AttributeRecordByAdminResponse
#   getAllVendorsRecordsByVendor(input: VendorsRecordsByVendorFilter): VendorsRecordsByVendorResponse!
#   getVendorRecordByVendor(input: VendorRecordByVendorInput!): VendorsRecordByVendorResponse!
#   getKycStatus(input: VendorRecordKycStatusInput!): VendorRecordKycStatusResponse!
}



# Schema

schema {
  mutation: Mutation
  query: Query
}
