scalar Upload
scalar JSONObject

# attribute value Mutations

type Mutation {
  createAttributeValue(input: CreateAttributeValueInput!): CreateAttributeResponse!
  editAttributeValue(input: AttributeValueEditInput!): AttributeValueEditResponse!
}


# attribute value Type

type AttributeValue {
  _id: String
  attributeId: String
  value: String
  colorCode: String
  priority: Int
  isBlocked: Boolean
}


# attribute value Input

input CreateAttributeValueInput {
  attributeId: String!
  value: String!
  colorCode: String!
  priority: Int!
  isBlocked: Boolean
} 


input AttributeValueEditInput {
  attributeValueId: String!
  value: String
  colorCode: String
  priority: Int
  isBlocked: Boolean
}


# attribute value Output

type CreateAttributeValueResponse {
  _id: String
  message: String
}

input AttributeValueRecordsByAdminFilter {
 page: Int,
 size: Int,
 isBlocked: Boolean
}

type AttributeValueRecordsByAdminResponse {
  maxRecords: Int!
  records: [Attribute!]
}

type AttributeValueEditResponse {
  _id: String
  attributeId: String
  value: String
  colorCode: String
  priority: Int
  isBlocked: Boolean
}

type Query {
  getAllAttributeValueRecordsByAdmin(input: AttributeValueRecordsByAdminFilter): AttributeValueRecordsByAdminResponse!
}

# Schema

schema {
  mutation: Mutation
  query: Query
}
