scalar ObjectId
scalar Upload


type Mutation {
  
  editDeliveryAgentData(input:EditAgentDataInput!,image:Upload):EditAgentDataInputResponse!
  # editDeliveryAgentData(input:EditAgentDataInput!):Boolean!
  createDeliveryAgent(input: CreateDeliveryAgentInput!,image:Upload): CreateDeliveryAgentResponse!
  suspendDeliveryAgent(input: SuspendDeliveryAgentInput!):CreateDeliveryAgentResponse!
  loginDeliveryAgent(input:LoginDeliveryAgentInput):LoginDeliveryAgentResponse!
  createSettlement(input:CreateSettlementInput!):CreateDeliveryAgentResponse!
  editSettlement(input: EditSettlementInput!):CreateDeliveryAgentResponse!
  orderAssignDeliveryAgent(input:OrderAssignDeliveryAgentInput!):OrderAssignDeliveryAgentResponse!
  orderDelivedbyAgent(input:OrderDelivedbyAgentInput!):OrderDelivedbyAgentResponse!
  

  }


type Query{
  
  getAllAgentData:[AllAgents]!
  getDeliveryAgent(input: GetDeliveryAgentInput!): DeliveryAgentResponse
  getAgentSettlementHistory(input: getAgentSettlementHistoryInput!):SettlementResponse!
  getAgentSettlementHistoryByAgent:[Settlement]!
  getDeliveryAgentByAgent(input: GetDeliveryAgentByAgentInput!): DeliveryAgentResponse
  getSettlementHistoryByAdmin:[Settlement]!
  getAllAssignOrderAgentProfile:GetAllAssignOrderAgentProfileResponse!
  getAssignedOrderByDeliveryAgent(input:GetAssignedOrderByDeliveryAgentInput):Boolean!
    
}


 input DeliveryAgentAssignedOrderInput{

     _id:ObjectId!
 }

 input GetAssignedOrderByDeliveryAgentInput{

        _id:ObjectId!
 }

 input getAgentSettlementHistoryInput{
       agentId:ObjectId!
         page: Int
        limit: Int
        startDate: Date
        endDate: Date
        type:String
 }


type OrderAssignDeliveryAgentResponse{

       status:Boolean!
      msg:String

}

type EditAgentDataInputResponse{

     status:Boolean!
      msg:String

}

type GetAllAssignOrderAgentProfileResponse{

      status:Boolean!
      msg:String
     
}

type ImageData {
  fileType: String
  fileURL: String
  mimeType: String
  originalName: String
}

type OrderDelivedbyAgentResponse{

        status:Boolean!
        msg:String

}




type AllAgents{
    _id:ObjectId!
    fullName:String!
    contactNumber:String!
    userID:String!
    password:String!
    agentType:String!
    isActive:Boolean!
    vendorID:ObjectId
    wallet:Wallet

}

type DeliveryAgent{
    _id:ObjectId!
    fullName:String!
    contactNumber:String!
    userID:String!
    ID:String
    agentType:String!
    isActive:Boolean!
    vendorID:ObjectId
    licence:ImageData
    wallet:Wallet
    settlementHistory:[SettlementHistory]
}

type DeliveryAgentResponse{
  deliveryAgent:DeliveryAgent
  totalItems:Float
  currentPage: Float
  totalPages: Float
}

type SettlementResponse{
  settlements:[Settlements]
  totalItems:Float
  currentPage: Float
  totalPages: Float

}

type Wallet {
  cashInHand:Float
  lastSettlementDate: Date
  totalSettlement:Float
  grandTotal: Float
}
input OrderDelivedbyAgentInput{

    
      orderItemId:ObjectId!
      pymentType:String!
      deliveryStatus:String!
      remarks:String

}


input OrderAssignDeliveryAgentInput{

       orderItemId:ObjectId!
       deliveryAgentId:ObjectId!
       deliveryAgentName:String
}



type Agent {
  _id: ObjectId
  fullName: String
  contactNumber:String
  wallet:Wallet
}

type Settlement {
  _id: ObjectId
  type: String
  agentId: Agent
  amount: Float
  date: Date
  remarks: String
  totalAmount: Float
  balance: Float
  createdAt:Date
  updatedAt:Date
}

type Settlements {
  _id: ObjectId
  type: String
  agentId: ObjectId
  amount: Float
  date: Date
  remarks: String
  totalAmount: Float
  balance: Float
  createdAt:Date
  updatedAt:Date
}

type SettlementHistory {
 _id: ObjectId
  type: String
  amount: Float
  remarks: String
  totalAmount: Float
  balance: Float
  createdAt:Date
}


# Response type for createDeliveryAgent Mutation
type CreateDeliveryAgentResponse {
  _id: ObjectId
  message: String!
}
 
# Input type for creating a Delivery Agent
input CreateDeliveryAgentInput {
  fullName: String!
  contactNumber: String!
  userID: String!
  password: String!
  agentType: String! # Must be one of: 'ArabDeals', 'Vendor', 'ThirdParty'
  vendorID: ObjectId # Optional, only for agents linked to a vendor
}

input CreateSettlementInput {
  agentId: ObjectId!
  amount: Float!
  remarks: String
}


input EditSettlementInput {
  settlementId: ObjectId!
  amount: Float!
  remarks: String
}

input SuspendDeliveryAgentInput {
  agentId:ObjectId!
  isActive:Boolean!
}

input GetDeliveryAgentInput {
  agentId:ObjectId!
  page: Int
  limit: Int
  startDate: Date
  endDate: Date
  type:String
}

input GetDeliveryAgentByAgentInput{
  page: Int
  limit: Int
  startDate: Date
  endDate: Date
  type:String
}

input EditAgentDataInput{

    _id:ObjectId!
    fullName:String!
    contactNumber:String!
    userID:String!
    agentType:String!
    vendorID:ObjectId

}

input LoginDeliveryAgentInput{
   
    userID:String!
    contactNumber:String!
    password:String!
}

type LoginDeliveryAgentResponse{

      status:String!
      fullName:String!
      token:String!
      msg:String!
}





# Schema

schema {
  mutation: Mutation
  query: Query
}



