scalar ObjectId
scalar Upload


type Mutation {
  
  editDeliveryAgentData(input:EditAgentDataInput!,image:Upload):EditAgentDataInputResponse!
  # editDeliveryAgentData(input:EditAgentDataInput!):Boolean!
  createDeliveryAgent(input: CreateDeliveryAgentInput!,image:Upload): CreateDeliveryAgentResponse!
  suspendDeliveryAgent(input: SuspendDeliveryAgentInput!):AllDeliveryAgentResponse!
  loginDeliveryAgent(input:LoginDeliveryAgentInput):LoginDeliveryAgentResponse!
  createSettlement(input:CreateSettlementInput!):AllDeliveryAgentResponse!
  editSettlement(input: EditSettlementInput!):AllDeliveryAgentResponse!
  orderAssignDeliveryAgent(input:OrderAssignDeliveryAgentInput!):OrderAssignDeliveryAgentResponse!
  orderDelivedbyAgent(input:OrderDelivedbyAgentInput!):OrderDelivedbyAgentResponse!
  returnOrderAssignDeliveryAgent(input:OrderAssignDeliveryAgentInput!):OrderAssignDeliveryAgentResponse!
  uploadReturnProductImageByAgent(input:UploadReturnInput!,image:[Upload]):UploadImageResponse!
  updateDeliveredMapLocation(input:UpdateMapLocation!):UploadImageResponse!
  returnStatusChangeDeliveryAgent(input:ReturnstatusUpdateInput!):ReturnstatusUpdateResponse!
  deliveryStatusOtpVerify(input:DeliveryStatusOtpVerifyInput!):DeliveryStatusOtpVerifyResponse!
  deliveryStatusAddDeliveryAgent(input:deliveryStatusAddDeliveryAgentInput!):deliveryStatusAddDeliveryAgentResponse!
  returnStatusChangeAfterOtpVerify(input:ReturnstatusUpdateInput!):ReturnstatusUpdateResponse!
  
  }


type Query{
  
  getAllAgentData(input:getAllAgentDataInput):getAllAgentDataResponse!
  getDeliveryAgent(input: GetDeliveryAgentInput!): DeliveryAgentResponse
  getAgentSettlementHistory(input: getAgentSettlementHistoryInput!):SettlementResponse!
  getAgentSettlementHistoryByAgent:[Settlement]!
  getDeliveryAgentByAgent(input: GetDeliveryAgentByAgentInput!): DeliveryAgentResponse
  getSettlementHistoryByAdmin:[Settlement]!
  getAllAssignOrderAgentProfile:GetAllAssignOrderAgentProfileResponse!
 
   getAssignedeOrderDeatilsByAgentProfile(input:getAssignedeOrderDeatilsByAgentProfileInput!):GetAssignedOrderDetailByDeliveryAgentResponseArry!
   getAssignedOrderByAgentProfile(input:getAssignedOrderByAgentProfileInput):getAssignedOrderByAgentProfileResponse!
   getAssignedOrderByDeliveryAgent(input:GetAssignedOrderByDeliveryAgentInput):GetAssignedOrderByDeliveryAgentResponse!

   getDeliveryAgentReturnOrder(input: GetDeliveryAgentReturnOrderInput!):GetDeliveryAgentReturnOrderResponse!
   getAssignedReturnOrderByAgent(input: GetAssignedReturnOrderInput!):GetDeliveryAgentReturnOrderResponse!
}


input DeliveryStatusOtpVerifyInput{
        orderItemId:ObjectId!
        code:String
        returnStatus:String
        returnRemark:String
        deliveryStatus:String
        paymentMode:String
        remarks:String
}

type DeliveryStatusOtpVerifyResponse{

        status:Boolean
        msg:String
}


input deliveryStatusAddDeliveryAgentInput{

      orderItemId:ObjectId!
      deliveryStatus:String!
      paymentMode:String
      remarks:String
}


type deliveryStatusAddDeliveryAgentResponse{

        status:Boolean
        msg:String
}





 input DeliveryAgentAssignedOrderInput{

     _id:ObjectId!
 }

 input GetDeliveryAgentReturnOrderInput{
      agentId:ObjectId!
      returnStatus:String
      page:Int
      limit:Int
 }

 input ReturnstatusUpdateInput{
  orderProductId:ObjectId!
  returnStatus:String!
  remarks:String!
 }

 type ReturnstatusUpdateResponse{
  status: Boolean!
  otp: Boolean!
  msg: String!
 }

 input UploadReturnInput{
  orderProductId:ObjectId!
 }

 input UpdateMapLocation{
  orderProductId:ObjectId!
  mapLocation:String!
 }

 type UploadImageResponse{
  message:String
 }

 input GetAssignedReturnOrderInput{
   returnStatus:String
    page:Int
    limit:Int
 }


type UserReturn {
  _id: ObjectId
  fullName: String
}

 type AdminReturnOrderProduct {
  _id: ObjectId
  userId: UserReturn
  productId: ObjectId
  vendorId: ObjectId
  vendorName: String
  orderId: String
  itemId: String
  productName: String
  shortDescription: String
  skuId: String
  warehouseSkuId: String
  image: FileData
  returnPeriod: Int
  mrp: Float
  sellingPrice: Float
  shippingCharge: Float
  paymentMode: String
  paymentStatus: String
  paymentRemark: String
  orderDate: Date
  shippingStatus: String
  shippedDate: Date
  deliveryDate: Date
  returnStatus: String
  returnUserReason: String
  returnAdminComment: String
  returnRequestDate: Date
  returnRejectedDate: Date
  returnDate: Date
  refundStatus: String
  refundAmount: Float
  refundRequestDate: Date
  refundDate: Date
  refundComment: String
  cancelUserReason: String
  cancelAdminComment: String
  cancelledDate: Date
  courierId: String
  invoiceNumber: String
  invoice: FileData
  deliveryAgentId: ObjectId
  deliveryBoy: DeliveryAgentForOrderProduct
  deliveryAgentName: String
  refundBankDetails: BankDetails
  returnAddress: returnAddress
  returnProductImage: [FileData]
  deliveryAssignedOn:Date
  returnOrderAssignedOn:Date
  returndeliveryAgentId: ObjectId
  returndeliveryAgentName: String
  returnCollectorBoy: DeliveryAgentForReturnOrderProduct
}

type GetDeliveryAgentReturnOrderResponse{
  records: [AdminReturnOrderProduct]!
  totalCount:Float
  page: Float
  totalPages: Float 
}


 input GetAssignedOrderByDeliveryAgentInput{

        _id:ObjectId!
        page:Int
        size:Int
        shippingStatus:String
 }

 input getAssignedOrderByAgentProfileInput{

    
        page:Int
        size:Int
        shippingStatus:String
 }




 type GetAssignedOrderByDeliveryAgentResponse{

  
     records: [GetAssignedOrderByDeliveryAgentResponseArry ],
     maxRecords: Int



   
     
 }

 input getAssignedeOrderDeatilsByAgentProfileInput{

        _id:ObjectId!
 }

 type  GetAssignedOrderByDeliveryAgentResponseArry{

      _id: ObjectId!
  orderId: String!
  userId: ObjectId!
  productName: String!
  itemId:String!
  sellingPrice: Float!
  paymentStatus: String!
  paymentMode:String
  orderDate: Date!
  shippingStatus: String!
  deliveryAgentId: ObjectId!
  userName: String
  email: String!
  mobileNumber: String!
   houseNumber: String
  streetName: String
  apartment: String
  suite: String
  unit: String
  city: String
  country: String
  postCode: String
 }

type GetAssignedOrderDetailByDeliveryAgentResponseArry{
  
      _id: ObjectId!
  orderId: String!
  userId: ObjectId!
  productName: String!
  itemId:String
  sellingPrice: Float!
  paymentStatus: String!
  paymentMode:String
  orderDate: Date!
  shippingStatus: String!
  deliveryAgentId: ObjectId!
  userName: String
  email: String!
  mobileNumber: String!
   houseNumber: String
  streetName: String
  apartment: String
  suite: String
  unit: String
  city: String
  country: String
  postCode: String
  returnStatus:String,
  returnUserReason:String,
  returnProductImage:[FileData],
  returnOrderAssignedOn:Date
  returnAddress: returnAddress
  returnAdminComment:String,
  returnRequestDate:Date,
  deliveyremark:String,
  cancelremark:String,
  postponedremark:String,
  deliveredMapLocation:String,
  deliveryAssignedOn:Date,
  returnRejectedDate:Date,
  returnRejectedRemarks:String,
  returnPostponedDate:Date,
  returnPostponedRemarks:String,
  returnCollectedDate:Date,
}
 
 type getAssignedeOrderDeatilsByAgentProfileResponse{

          _id: ObjectId!
  orderId: String!
  userId: ObjectId!
  productName: String!
  sellingPrice: Float!
  paymentStatus: String!
  orderDate: String!
  shippingStatus: String!
  deliveryAgentId: ObjectId!
  userName: String
  email: String!
  mobileNumber: String!
   houseNumber: String
  streetName: String
  apartment: String
  suite: String
  unit: String
  city: String
  country: String
  postCode: String
        
 }


type getAssignedOrderByAgentProfileResponse {
     records: [GetAssignedOrderByDeliveryAgentResponseArry ],
     maxRecords: Int
 }

#  type getAssignedOrderDetailByAgentProfileResponse {
#      records: [GetAssignedOrderDetailByDeliveryAgentResponseArry ],
#      maxRecords: Int  
#  }










 input getAgentSettlementHistoryInput{
       agentId:ObjectId!
         page: Int
        limit: Int
        startDate: Date
        endDate: Date
        type:String
 }

 type getAllAgentDataResponse{

    maxRecords: Int!
    records: [AllAgents]
      
}



input getAllAgentDataInput{
 
    page: Int
    size: Int
    isActive:String
    agentType:String
    search:String
    settlement:Boolean
         
}


type OrderAssignDeliveryAgentResponse{

       status:Boolean!
      msg:String

}

type EditAgentDataInputResponse{

     status:Boolean!
      msg:String

}

type GetAllAssignOrderAgentProfileResponse{

      status:Boolean!
      msg:String
     
}

type ImageData {
  fileType: String
  fileURL: String
  mimeType: String
  originalName: String
}

type OrderDelivedbyAgentResponse{

        status:Boolean!
        msg:String
        otp:Boolean

}




type AllAgents{
    _id:ObjectId!
    fullName:String!
    contactNumber:String!
    userID:String!
    password:String!
    agentType:String!
    isActive:Boolean!
    vendorID:ObjectId
    wallet:Wallet

}

type DeliveryAgent{
    _id:ObjectId!
    fullName:String!
    contactNumber:String!
    userID:String!
    ID:String
    agentType:String!
    isActive:Boolean!
    vendorID:ObjectId
    licence:ImageData
    wallet:Wallet
    lastSettlementID:ObjectId
    settlementHistory:[SettlementHistory]
}

type DeliveryAgentResponse{
  deliveryAgent:DeliveryAgent
  totalItems:Float
  currentPage: Float
  totalPages: Float
}

type SettlementResponse{
  settlements:[Settlements]
  totalItems:Float
  currentPage: Float
  totalPages: Float

}

type Wallet {
  cashInHand:Float
  lastSettlementDate: Date
  totalSettlement:Float
  grandTotal: Float
  numberOfOrderAssigned:Float
  numberOfOrderDelivered:Float
  numberOfReturnOrderAssigned:Float
  numberOfReturnOrderDelivered:Float
  numberOfPendingReturns:Float
  numberOfPendingOrdes:Float

}
input OrderDelivedbyAgentInput{

    
      orderItemId:ObjectId!
      deliveryStatus:String!
      remarks:String

}


input OrderAssignDeliveryAgentInput{
       orderItemId:ObjectId!
       deliveryAgentId:ObjectId!
       deliveryAgentName:String
}



type Agent {
  _id: ObjectId
  fullName: String
  contactNumber:String
  wallet:Wallet
}

type Settlement {
  _id: ObjectId
  type: String
  agentId: Agent
  amount: Float
  date: Date
  remarks: String
  totalAmount: Float
  balance: Float
  createdAt:Date
  updatedAt:Date
}

type Settlements {
  _id: ObjectId
  type: String
  agentId: ObjectId
  amount: Float
  date: Date
  remarks: String
  totalAmount: Float
  balance: Float
  createdAt:Date
  updatedAt:Date
}

type SettlementHistory {
 _id: ObjectId
  type: String
  amount: Float
  remarks: String
  totalAmount: Float
  balance: Float
  createdAt:Date
}


# Response type for createDeliveryAgent Mutation
type AllDeliveryAgentResponse {
  _id: ObjectId
  message: String!
}
 
# Response type for createDeliveryAgent Mutation
type CreateDeliveryAgentResponse {
  _id: ObjectId
  message: String!
  error:Boolean
}
 
# Input type for creating a Delivery Agent
input CreateDeliveryAgentInput {
  fullName: String!
  contactNumber: String!
  userID: String!
  password: String!
  agentType: String! # Must be one of: 'ArabDeals', 'Vendor', 'ThirdParty'
  vendorID: ObjectId # Optional, only for agents linked to a vendor
}

input CreateSettlementInput {
  agentId: ObjectId!
  amount: Float!
  remarks: String
}


input EditSettlementInput {
  settlementId: ObjectId!
  amount: Float!
  remarks: String
}

input SuspendDeliveryAgentInput {
  agentId:ObjectId!
  isActive:Boolean!
}

input GetDeliveryAgentInput {
  agentId:ObjectId!
  page: Int
  limit: Int
  startDate: Date
  endDate: Date
  type:String
}

input GetDeliveryAgentByAgentInput{
  page: Int
  limit: Int
  startDate: Date
  endDate: Date
  type:String
}

input EditAgentDataInput{

    _id:ObjectId!
    fullName:String!
    contactNumber:String!
    userID:String!
    agentType:String!
    vendorID:ObjectId

}

input LoginDeliveryAgentInput{
   
    userID:String!
    contactNumber:String!
    password:String!
}

type LoginDeliveryAgentResponse{

      status:String!
      fullName:String!
      token:String!
      msg:String!
}





# Schema

schema {
  mutation: Mutation
  query: Query
}



