scalar ObjectId

# Delivery Agent Type
type DeliveryAgent {
  id: ID!
  fullName: String!
  contactNumber: String!
  userID: String!
  agentType: String!
  isActive: Boolean!
  vendorID: ObjectId
}

# Response type for createDeliveryAgent Mutation
type CreateDeliveryAgentResponse {
  _id: ObjectId
  message: String!
}

# Input type for creating a Delivery Agent
input CreateDeliveryAgentInput {
  fullName: String!
  contactNumber: String!
  userID: String!
  password: String!
  agentType: String! # Must be one of: 'ArabDeals', 'Vendor', 'ThirdParty'
  vendorID: ObjectId # Optional, only for agents linked to a vendor
}

# Mutation for creating a Delivery Agent
type Mutation {
  createDeliveryAgent(input: CreateDeliveryAgentInput!): CreateDeliveryAgentResponse!
}

type Query{

   # view all DeliveryAgents details query
   viewAllDeliveryAgents:DeliveryAgent!
    
}

# Schema

schema {
  mutation: Mutation
}



