scalar Upload

# Vendor auth Mutations

type Mutation {
  createTempVendor(input: tempVendorSignUpInput!): AddTempVendorResponse!
}

type ImageData {
  fileType: String
  fileURL: String
  mimeType: String
  originalName: String
}

# Vendor auth Type

type tempVendor {
  _id: String
  fullName: String
  mobileNumber: String
}

# Vendor auth Input

input tempVendorSignUpInput {
  fullName: String!
  mobileNumber: String!
}


# Vendor auth Output

type AddTempVendorResponse {
  _id: String!
  mobileNumber: String!
}

# Schema

schema {
  mutation: Mutation
  query: Query
}
