scalar Upload
scalar JSONObject

# Vendor  Mutations

type Mutation {
  createVendor(input: VendorSignUpInput!, images:[Upload], fileMap: JSONObject): CreateVendorResponse!
  vendorAccountApproval(input: VendorAccountApprovalInput!): VendorAccountApprovalResponse!
  loginVendor(input: VendorLoginInput!): VendorAuthResponse!
  updateVendorProfile(input: VendorEditProfileInput!, image: Upload): UpdateVendorResponse!
}

# Vendor  Type


type ImageData {
  fileType: String
  fileURL: String
  mimeType: String
  originalName: String
}

type Vendor {
  _id: String
  email: String
  password: String
  fullName: String
  mobileNumber: String
  country: String
  brand: String
  profilePic: ImageData
  isBlocked: Boolean
  companyName: String 
  businessOutletName: String 
  outletName: String   
  crNumber: String     
  crLicence: String    
  businessLicence: String  
  chamberOfCommerceCertificate: String  
  companyType: String   
  businessAddress: String  
  contactPerson: ContactPersonData  
  exteriorImage: ImageData  
  interiorImage: ImageData  
  sellingProductDetails: String  
  sellingProductBrands: String   
  isVerified: Boolean
  isApproved: Boolean
}

type MobileOtpData {
  code: String
  expiresAt: String
}

type ContactPersonData {
  name: String
  phoneNumber: String
  designation: String
}

# Vendor  Input

input VendorSignUpInput {
  email: String!
  password: String!
  fullName: String!
  mobileNumber: String!
  country: String!
  brand: String!
  companyName: String!
  businessOutletName: String!
  outletName: String!   
  crNumber: String!     
  crLicence: String!    
  businessLicence: String!  
  chamberOfCommerceCertificate: String!  
  companyType: String!   
  businessAddress: String!  
  contactPerson: ContactPersonInput!   
  sellingProductDetails: String!  
  sellingProductBrands: String!   
}


input VendorLoginInput {
  email: String!
  password: String!
}

input VendorEditProfileInput {
  fullName: String
  email: String
  password: String
  mobileNumber: String
  country: String
  brand: String
}

input MobileOtpDataInput {
  code: String
  expiresAt: String
}

input ContactPersonInput {
  name: String!
  phoneNumber: String!
  designation: String!
}

input VendorAccountApprovalInput {
  _id: String!
  approvalStatus: Boolean!
}

# Vendor  Output

type VendorAuthResponse {
  _id: String
  token: String
}

type UpdateVendorResponse {
  _id: String
  message: String
}

type VendorAccountApprovalResponse {
  _id: String,
  message: String
}

type Query {
  getAllVendorsRecordsByAdmin(input: VendorsRecordsByAdminFilter): VendorsRecordsResponse!
  getVendorRecordByAdmin(input: VendorRecordByAdminFilter!): VendorRecordResponse!
}

# Vendor  type

type getVendorRecordResponse {
  record: Vendor
}

type CreateVendorResponse{
    _id: String
    message: String
}

# Vendor  input

 input VendorsRecordsByAdminFilter {
    page: Int
    size: Int
  }


 input VendorRecordByAdminFilter {
    _id: String!
  }

  type VendorsRecordsResponse {
    maxRecords: Int!
    records: [Vendor]
    message: String
  }   

  type VendorRecordResponse {
    record: Vendor!
    message: String
  }


# Schema

schema {
  mutation: Mutation
  query: Query
}
