scalar Upload
scalar JSONObject

# Vendor  Mutations

type Mutation {
  createVendor(input: VendorSignUpInput!, image:Upload): CreateVendorResponse!
  createVendorByAdmin(input: VendorSignUpByAdminInput!, image:Upload): CreateVendorByAdminResponse!
  vendorAccountApproval(input: VendorAccountApprovalInput!): VendorAccountApprovalResponse!
  loginVendor(input: VendorLoginInput!): VendorAuthResponse!
  updateVendorProfile(input: VendorEditProfileInput!,image: Upload): UpdateVendorResponse!
}

# Vendor  Type


type ImageData {
  fileType: String
  fileURL: String
  mimeType: String
  originalName: String
}

type Vendor {
  _id: String
  fullName: String!
  email: String
  mobileNumber: String!
  isBlocked: Boolean
  isKycCompleted: Boolean
  brands: [BrandRecordId]
  categories: [CategoryRecordId]
}

type VendorWithKycData {
  _id: String
  fullName: String
  email: String
  mobileNumber: String
  isBlocked: String
  isKycCompleted: Boolean
  outletId: String
  outletName: String
  outletStatus: String
  companyId: String
  companyName: String
  companyStatus: String
}

type MobileOtpData {
  code: String
  expiresAt: String
}

type ContactPersonData {
  name: String
  phoneNumber: String
  designation: String
}

# Vendor  Input

input VendorSignUpInput {
  fullName: String!
  email: String
  mobileNumber: String!
  isBlocked: Boolean
  isKycCompleted: Boolean
  brands: [BrandRecordIdInput]
  categories: [CategoryRecordIdInput]
}

input VendorSignUpByAdminInput {
  fullName: String!
  email: String
  mobileNumber: String!
  isBlocked: Boolean
  isKycCompleted: Boolean
  brands: [BrandRecordIdInput]
  categories: [CategoryRecordIdInput]
}

input VendorLoginInput {
  email: String!
  password: String!
}

input VendorEditProfileInput {
   _id: String!
  fullName: String
  email: String
  mobileNumber: String
  isKycCompleted: Boolean
  password: String
}

input MobileOtpDataInput {
  code: String
  expiresAt: String
}

input ContactPersonInput {
  name: String!
  phoneNumber: String!
  designation: String!
}

input VendorAccountApprovalInput {
  _id: String!
  approvalStatus: Boolean!
}

# Vendor  Output

type VendorAuthResponse {
  _id: String
  token: String
}

type UpdateVendorResponse {
  _id: String
  message: String
}

type VendorAccountApprovalResponse {
  _id: String,
  message: String
}

type Query {
  getAllVendorsRecordsByAdmin(input: VendorsRecordsByAdminFilter): VendorsRecordsResponse!
  getVendorRecordByAdmin(input: VendorRecordByAdminFilter!): VendorRecordResponse!
}

# Vendor type

type CreateVendorResponse{
    _id: String
    message: String
    token: String
}

type CreateVendorByAdminResponse{
    _id: String
    message: String
    token: String
}

# Vendor  input

 input VendorsRecordsByAdminFilter {
    page: Int
    size: Int
  }


 input VendorRecordByAdminFilter {
    _id: String!
  }

  type VendorsRecordsResponse {
    maxRecords: Int!
    records: [VendorWithKycData]
    message: String
  }   

  type VendorRecordResponse {
    record: Vendor!
    message: String
  }


# Schema

schema {
  mutation: Mutation
  query: Query
}
