  scalar Upload
  scalar JSONObject

# Brand Mutations


  type Mutation {
    addVendorOutlet(input: AddVendorOutletInput!, images:[Upload], fileMap: JSONObject): AddVendorOutletResponse!
    updateBrand(input: updateBrandInput!, image:Upload): updateBrandResponse!
    deleteBrand(input: BrandIdInput!): BrandDeleteRecordResponse!
  }

   # Type

   type VendorOutlet {
        _id: String
        vendorId: String
        outletName:String
        country:String
        district: String
        village: String
        address: String
        contactPersonName: String
        contactPersonNumber: String
        contactPersonDesignation: String
        status: String
        remarks: [String]
    }  


    # Input

    input AddVendorOutletInput {
        vendorId: String!
        outletName:String
        country:String
        district: String
        village: String
        address: String
        contactPersonName: String
        contactPersonNumber: String
        contactPersonDesignation: String
    }   

    input updateBrandInput {
         _id: String!
        brandName: String
        isBlocked: Boolean
    }

    input BrandRecordIdInput {
      _id: String
    }

    # Output

    type AddVendorOutletResponse {
        _id: String!
        message: String
    }  

    type updateBrandResponse {
        _id: String!
        message: String
    }

    type BrandDeleteRecordResponse {
      _id: String!
      message: String
    }
     
    type BrandRecordId {
      _id: String
    }
 


# Brand Queries

  type Query {
    getAllBrandRecordsByAdmin(input: BrandRecordsFilter): BrandRecordsResponse!
    getBrandRecordByAdmin(input: BrandIdInput!): BrandRecordResponse!
  }   

    # Input
   
  input BrandIdInput {
    _id: String!
  }

  input BrandRecordsFilter {
    page: Int
    size: Int
  }

    # Output

    type ImageData {
    fileType: String
    fileURL: String
    mimeType: String
    originalName: String
  }    

  type BrandRecord {
    _id: String
    brandName: String
    isBlocked: Boolean
    logo: ImageData
  }  
  
  type BrandRecordResponse {
    record: BrandRecord!
  }

  type BrandRecordsResponse {
    maxRecords: Int!
    records: [BrandRecord!]
    message: String
  }
    


# Schema

schema {
    mutation: Mutation,
    query:Query
}

