  scalar Upload
  scalar JSONObject
  scalar ObjectId

# Outlet Mutations


  type Mutation {
    addVendorOutlet(input: AddVendorOutletInput!, images:[Upload], fileMap: JSONObject): AddVendorOutletResponse!
    updateVendorOutlet(input: UpdateVendorOutletInput!, images:[Upload], fileMap: JSONObject): UpdateVendorOutletResponse!
    updateVendorOutletByAdmin(input: UpdateVendorOutletByAdminInput!,outletLicense:Upload,interiorImage: Upload, exteriorImage:Upload): UpdateVendorOutletByAdminResponse!

  }




   # Type

  type ImageData {
    fileType: String
    fileURL: String
    mimeType: String
    originalName: String
  }  

   type VendorOutlet {
        _id: String
        vendorId: String
        outletName:String
        country:String
        district: String
        village: String
        address: String
        contactPersonName: String
        contactPersonNumber: String
        contactPersonDesignation: String
        status: String
        remarks: [String]
        outletLicense: ImageData
        interiorImage: ImageData
        exteriorImage: ImageData
    }  

    type vendorOutletRecordsWithKycData {
      vendorId: String
      fullName: String
      isKycCompleted: String
      _id: String
      outletName: String
      status: String
      country: String
      district: String
      village: String
      address: String
      contactPersonName: String
      contactPersonNumber: String
      contactPersonDesignation: String
      remarks: [String]
    }


    # Input

    input AddVendorOutletInput {
        outletName:String!
        country:String!
        district: String!
        village: String!
        address: String!
        contactPersonName: String!
        contactPersonNumber: String!
        contactPersonDesignation: String!
    }   

    input UpdateVendorOutletInput {
        outletName:String
        country:String
        district: String
        village: String
        address: String
        contactPersonName: String
        contactPersonNumber: String
        contactPersonDesignation: String
    }

    input UpdateVendorOutletByAdminInput {
      _id: ObjectId!
      outletName:String
      country:String
      district: String
      village: String
      address: String
      contactPersonName: String
      contactPersonNumber: String
      contactPersonDesignation: String
      status: String
      remarks: [String!]
    }



    input DeleteVendorOutletIdInput {
      _id: String!
    }

    input VendorOutletStatusUpdationInput {
      _id: String!
      status: String!
      remarks: [String]
    } 

    # Output

    type AddVendorOutletResponse {
        _id: String!
        message: String
    }  

    type UpdateVendorOutletResponse {
        message: String
    }

    type DeleteVendorOutletRecordResponse {
      _id: String!
      message: String
    }
 
   type UpdateVendorOutletByAdminResponse {
        message: String
  }


# Outlet Queries

  type Query {
    getAllVendorOutletRecordsByAdmin(input: VendorOutletRecordsByAdminFilter): VendorOutletRecordsByAdminResponse!
    getVendorOutletRecordByAdmin(input: VendorOutletRecordByAdminInput!): VendorOutletRecordByAdminResponse!
    getVendorOutletRecord: VendorOutletRecordResponse!

  }   

    # Input
   
  input VendorOutletRecordByAdminInput {
    _id: String!
  }

  input VendorOutletRecordsByAdminFilter {
    page: Int
    size: Int
    status: String
    vendorId:ObjectId
    outletName:String
    fullName:String
  }

    # Output

    type ImageData {
    fileType: String
    fileURL: String
    mimeType: String
    originalName: String
  }    

  type VendorOutletRecordByAdminResponse {
    record: VendorOutlet!
    message: String
  }

  type VendorOutletRecordResponse {
    record: VendorOutlet!
    message: String
  }

  type VendorOutletRecordsByAdminResponse {
    maxRecords: Int!
    records: [vendorOutletRecordsWithKycData!]
    message: String
  }

  type VendorOutletStatusUpdationResponse {
    _id: String
    status: String
    message: String
  }
    
# Schema

schema {
    mutation: Mutation,
    query:Query
}

