scalar Upload
scalar JSONObject

# attribute  Mutations

type Mutation {
  createAttribute(input: CreateAttributeInput!): CreateAttributeResponse!
  editAttribute(input: AttributeEditInput!): AttributeEditResponse!
}


# attribute  Type

type ImageData {
  fileType: String
  fileURL: String
  mimeType: String
  originalName: String
}

type Attribute {
  _id: String
  attributeType: String
  name: String
  description: String
  isBlocked: Boolean
}

type AttributeValueRecord {
  _id: String
  value: String
  colorCode: String
  priority: Int
  isBlocked: Boolean
} 

type AttributeWithValue {
  _id: String
  attributeType: String
  name: String
  description: String
  attributeValues:[AttributeValueRecord]
  isBlocked: Boolean
}

type CategoryWithCategory{
  _id: String,
  categoryName: String
  attributes: [AttributeWithValue]
}


# attribute  Input

input CreateAttributeInput {
  attributeType: String!
  name: String!
  description: String!
  isBlocked: Boolean
} 


input AttributeEditInput {
  attributeId: String!
  attributeType: String
  name: String
  description: String
  isBlocked: Boolean
}


# attribute  Output

type CreateAttributeResponse {
  _id: String
  message: String
}

type AttributeEditResponse {
  _id:String
  attributeType: String
  name: String
  description: String
  isBlocked: Boolean
  message: String
}

input AttributeRecordsByAdminFilter {
 page: Int,
 size: Int,
 isBlocked: Boolean
}

input AttributeRecordByAdminInput {
  attributeId: String!
}

input AttributeRecordByVendorInput {
  attributeId: String!
}

input AttributesDetailsWithCategoryIdInput {
  categoryId: String!
}

type AttributeRecordsByAdminResponse {
  maxRecords: Int!
  records: [Attribute!]
}

type AttributeRecordByAdminResponse {
  record: AttributeWithValue
  message: String
}

type AttributeRecordByVendorResponse {
  record: AttributeWithValue
  message: String
}

type AttributesDetailsWithCategoryResponse {
  record: CategoryWithCategory
  message: String
}

type Query {
  getAllAttributeRecordsByAdmin(input: AttributeRecordsByAdminFilter): AttributeRecordsByAdminResponse!
  getAttributeRecordByAdmin(input:  AttributeRecordByAdminInput!): AttributeRecordByAdminResponse
  getAttributeRecordByVendor(input:  AttributeRecordByVendorInput!): AttributeRecordByVendorResponse
  getAttributeRecordsByAdmin(input:  AttributeRecordByAdminInput!): AttributeRecordByAdminResponse  
  getAttributesDetailsWithCategory(input: AttributesDetailsWithCategoryIdInput!): AttributesDetailsWithCategoryResponse
  getAttributesDetailsWithCategoryByAdmin(input: AttributesDetailsWithCategoryIdInput!): AttributesDetailsWithCategoryResponse
}



# Schema

schema {
  mutation: Mutation
  query: Query
}
