export const collections = {
    PRODUCTS: "products",
    CATEGORIES: "categories",
    ADMINS: "admins",
    VENDORS: "vendors",
    AUTH_UTILITIES: "auth_utilities",
    VENDOR_COMPANIES: "vendor_companies",
    VENDOR_OUTLETS: "vendor_outlets",
    BRANDS: "brands",
    ATTRIBUTES: "attributes",
    ATTRIBUTE_VALUES: "attribute_values",
    USERS:"users",
    CARTS:"carts",
    CMS:"cms",
}