export const collections = {
    PRODUCTS: "products",
    CATEGORIES: "categories",
    ADMINS: "admins",
    DELIVERYAGENT:"deliveryagents",
    SETTLEMENTS:"settlements",
    VENDORS: "vendors",
    AUTH_UTILITIES: "auth_utilities",
    VENDOR_COMPANIES: "vendor_companies",
    VENDOR_OUTLETS: "vendor_outlets",
    BRANDS: "brands",
    ATTRIBUTES: "attributes",
    ATTRIBUTE_VALUES: "attribute_values",
    USERS: "users",
    CARTS: "carts",
    CMS: "cms",
    WISHLISTS: "wishlists",
    USER_SHIPPING_ADDRESS: "user_shipping_address",
    SHIPPING_CONFIGS: "shipping_configs",
    PAYMENT_CONFIGS: "payment_configs",
    ORDERS: "orders",
    ORDER_PRODUCTS: "order_products",
    COUNTRIES: "countries",
    JOBS: "jobs",
    DELIVERY_AGENT_CONFIGS: "delivery_agent_configs",
    COUPONS:"coupons",
    ROLES:"roles",
    NOTIFICATION:"notification",
    RETURN_POLICY:"return_policies",
    WARRANTY_POLICY:"warranty_policies"
}