  scalar Upload

# Brand Mutations


  type Mutation {
    addBrand(input: AddBrandInput!, image:Upload): AddBrandResponse!
    updateBrand(input: updateBrandInput!, , image:Upload): updateBrandResponse!
    deleteBrand(input: BrandIdInput!): BrandDeleteRecordResponse!
  }


    # Input

    input AddBrandInput {
        brandName:String!
        isBlocked: Boolean
        isPopular: Boolean
        priority: Int!
    }   

    input updateBrandInput {
          _id: String!
        brandName: String
        isBlocked: Boolean
        isPopular: Boolean
        priority: Int
    }

    input BrandRecordIdInput {
      _id: String
    }

    # Output

    type AddBrandResponse {
        _id: String!
        message: String
    }  

    type updateBrandResponse {
        _id: String!
        message: String
    }

    type BrandDeleteRecordResponse {
      _id: String!
      message: String
    }
     
    type BrandRecordId {
      _id: String
    }
 


# Brand Queries

  type Query {
    getAllBrandRecordsByAdmin(input: BrandRecordsFilter): BrandRecordsResponse!
    getBrandRecordByAdmin(input: BrandIdInput!): BrandRecordResponse!
    getAllBrandRecordsWithVendorByAdmin(input: VendorInput!): BrandRecordsWithVendorResponse!
  }   

    # Input
   
  input BrandIdInput {
    _id: String!
  }

  input VendorInput {
    vendorId: String!
    page: Int
    size: Int
  }

  input BrandRecordsFilter {
    page: Int
    size: Int
    isBlocked: Boolean
  }

    # Output

    type ImageData {
    fileType: String
    fileURL: String
    mimeType: String
    originalName: String
  }    

  type BrandRecord {
    _id: String
    brandName: String
    isBlocked: Boolean
    logo: ImageData
    isPopular: Boolean
    priority: Int
  }  
  
  type BrandRecordResponse {
    record: BrandRecord!
    message: String
  }

  type BrandRecordsResponse {
    maxRecords: Int!
    records: [BrandRecord!]
    message: String
  }

  type BrandRecordsWithVendorResponse {
    maxRecords: Int!
    records: [BrandRecord!]
    message: String
  }
    


# Schema

schema {
    mutation: Mutation,
    query:Query
}

