  scalar Upload
  scalar ObjectId

# Brand Mutations


  type Mutation {
    addBrand(input: AddBrandInput!, image:Upload): AddBrandResponse!
    updateBrand(input: updateBrandInput!, , image:Upload): updateBrandResponse!
    deleteBrand(input: BrandIdInput!): BrandDeleteRecordResponse!
  }


    # Input

    input AddBrandInput {
        brandName:String!
        isBlocked: Boolean
        isPopular: Boolean
        priority: Int!
    }   

    input updateBrandInput {
          _id: String!
        brandName: String
        isBlocked: Boolean
        isPopular: Boolean
        priority: Int
        categories: [String]
    }

    input BrandRecordIdInput {
      _id: String
    }

    input BrandsDetailsWithCategoryIdInput {
      categoryId: ObjectId
    }

    input BrandsDetailsWithCategoryIdInMobileInput {
      categoryId: ObjectId
    }

    # Output

    type AddBrandResponse {
        _id: String!
        message: String
    }  

    type updateBrandResponse {
        _id: String!
        message: String
    }

    type BrandDeleteRecordResponse {
      _id: String!
      message: String
    }
     
    type BrandRecordId {
      _id: String
    }

    # type BrandsWithCategory{
    #   _id: String,
    #   categoryName: String
    #   brands: [BrandRecord]
    # }

    type BrandsDetailsWithCategoryResponse {
      records: [BrandRecord]
      message: String
    }

    type BrandsDetailsWithCategoryInMobileResponse {
      records: [BrandRecord]
      message: String
    }

 


# Brand Queries

  type Query {
    getAllBrandRecordsByAdmin(input: BrandRecordsFilter): BrandRecordsResponse!
    getAllTopBrandRecords(input: BrandRecordsFilter): BrandRecordsResponse!
    getBrandRecordByAdmin(input: BrandIdInput!): BrandRecordResponse!
    getAllBrandRecordsWithVendorByAdmin(input:  getAllBrandRecordsWithVendorByAdminInput!): BrandRecordsWithVendorByAdminResponse!
    getAllBrandRecordsWithVendorByVendor(input:  getAllBrandRecordsWithVendorByVendorInput!): BrandRecordsWithVendorByVendorResponse!
    getBrandDetailsWithCategory(input: BrandsDetailsWithCategoryIdInput!):BrandsDetailsWithCategoryResponse!
    getBrandDetailsWithCategoryInMobile(input: BrandsDetailsWithCategoryIdInMobileInput!):BrandsDetailsWithCategoryInMobileResponse!
    getCategoryDetailsWithBrand(input: CategoriesDetailsWithBrandIdInput!):CategoriesDetailsWithBrandResponse!

    # Mobile API
    getAllTopBrandRecordsInMobile(input: BrandRecordsInMobileFilter): BrandRecordsInMobileResponse!
  }   

    # Input
   
  input BrandIdInput {
    _id: String!
  }

  input getAllBrandRecordsWithVendorByAdminInput {
    vendorId: String!
    page: Int
    size: Int
  }

  input getAllBrandRecordsWithVendorByVendorInput {
    page: Int
    size: Int
    query:String
  }


  input BrandRecordsFilter {
    page: Int
    size: Int
    isBlocked: Boolean
    query:String
    paginationEnabled:Boolean
  }

   input BrandRecordsInMobileFilter {
    page: Int
    size: Int
    isBlocked: Boolean
  }

  input CategoriesDetailsWithBrandIdInput {
    brandId: String!
  }

    # Output

    type ImageData {
    fileType: String
    fileURL: String
    mimeType: String
    originalName: String
  }    

  type BrandRecord {
    _id: String
    brandName: String
    isBlocked: Boolean
    logo: ImageData
    isPopular: Boolean
    priority: Int
  }  
 
  
  type BrandRecordResponse {
    record: BrandRecord!
    message: String
  }

  type BrandRecordsResponse {
    maxRecords: Int!
    records: [BrandRecord!]
    message: String
  }

  type BrandRecordsInMobileResponse {
    maxRecords: Int!
    records: [BrandRecord!]
    message: String
  }

  type BrandRecordsWithVendorByAdminResponse {
    maxRecords: Int!
    records: [BrandRecord!]
    message: String
  }

  type BrandRecordsWithVendorByVendorResponse {
    maxRecords: Int!
    records: [BrandRecord!]
    message: String
  }

  type CategoriesDetailsWithBrandResponse {
   records: BrandDetailsWithCategory
  }

  type BrandDetailsWithCategory {
    brandId: String,
    brandName: String,
    categories: [CategoryInBrands]
    message: String
  }

    type CategoryInBrands{
    categoryName:String
    _id: String
    isBlocked: Boolean
    fullCategoryName: String
    isLeaf: Boolean
    description: String
  } 
    


# Schema

schema {
    mutation: Mutation,
    query:Query
}

