  scalar Upload
  scalar JSONObject

# Cms Mutations


  type Mutation {
    addCms2Section(input: Cms2AddInput!, images:[Upload]): Cms2AddResponse!
    updateCms2Record(input: UpdateCms2Input!, images:[Upload], fileMap: JSONObject): UpdateCms2Response!
    deleteCms2Record(input: Cms2RecordId!): DeleteCms2Response!
  }



    # Input

    input Cms2AddInput {
        pageName: String!
        title: String
        subTitle: String
        items: [Cms2ItemsInput]
    }


    input Cms2ButtonDataInput {
        buttonText: String
        redirectionURL: String
    }


    input Cms2ItemsInput {
        title: String
        subTitle: String
        button: Cms2ButtonDataInput
    }

      input Cms2ItemsUpdateInput {
        _id: String
        title: String
        subTitle: String
        button: Cms2ButtonDataInput
    }

       input UpdateCms2Input {
        _id: String!
        pageName: String
        title: String
        subTitle: String
        sectionName: String
        items: [Cms2ItemsUpdateInput]
    }

    input Cms2RecordId {
        _id: String!
    }

    # Output

    type Cms2AddResponse {
        _id: String!
        message: String
    }

    type UpdateCms2Response {
      record: Cms2Record
      message: String
    }

    type DeleteCms2Response {
      _id: String!
      message: String
    }



# Cms Queries

 type Query {
  getCms2Record(input: cms2RecordFilter!): Cms2RecordResponse!
  getAllCms2Records(input: Cms2RecordsFilter): Cms2RecordsResponse!
  getAllCms2RecordsByAdmin(input: Cms2RecordsByAdminFilter): Cms2RecordsResponse!
  getCms2RecordByAdmin(input: cms2RecordByAdminFilter!): Cms2RecordResponse!
}   

    # Input

  input cms2RecordByAdminFilter {
    _id: String!
  }    
   
  input cms2RecordFilter {
    sectionName: String!
  }

   input Cms2RecordsFilter {
    _id: String
    page: Int
    size: Int
    pageName: String
    sectionName: String
    title: String
    subTitle: String
    description: [String]
    images: [String]
    buttons: [String]  
  }

   input Cms2RecordsByAdminFilter {
    _id: String
    page: Int
    size: Int
    pageName: String
    sectionName: String
    title: String
    subTitle: String
    description: [String]
    images: [String]
    buttons: [String]  
  }

    # Output

  type Cms2ButtonData {
    buttonText: String
    redirectionURL: String
  }

  type Cms2ImageData {
    fileType: String
    fileURL: String
    mimeType: String
    originalName: String
  }  


  type Cms2ItemsData {
    _id: String
    title: String
    subTitle: String
    button: Cms2ButtonData
    image: Cms2ImageData
  }

  type Cms2Record {
    _id: String
    pageName: String
    sectionName: String
    title: String
    subTitle: String
    items: [Cms2ItemsData]
  }  
  
  type Cms2RecordResponse {
    record: Cms2Record!
    message: String
  }
    
   type Cms2RecordsResponse {
    maxRecords: Int!
    records: [Cms2Record!]
    message: String
  }   

# Schema

schema {
    mutation: Mutation,
    query:Query
}

