scalar Upload
scalar ObjectId
scalar Date


# User Order  Mutations

type Mutation {
    createUserOrder(input: CreateUserOrderInput!): CreateUserOrderResponse!
    updateAdminOrderProduct(input: UpdateAdminOrderProductInput!, invoice:Upload): UpdateAdminOrderProductResponse!
    returnUserOrderProduct(input: ReturnUserOrderProductInput!): ReturnUserOrderProductResponse!
    cancelUserOrderProduct(input: CancelUserOrderProductInput!): CancelUserOrderProductResponse!

    # Mobile side api's
    createUserOrderInMobile(input: CreateUserOrderInMobileInput!): CreateUserOrderInMobileResponse!
    returnUserOrderProductInMobile(input: ReturnUserOrderProductInMobileInput!): ReturnUserOrderProductInMobileResponse!
    cancelUserOrderProductInMobile(input: CancelUserOrderProductInMobileInput!): CancelUserOrderProductResponse!
}


# Create Order Input

input CreateUserOrderInput {
    shippingAddressId: ObjectId!
    paymentMode: String!
    grandTotal: Float!
}

input CreateUserOrderInMobileInput {
    shippingAddressId: ObjectId!
    paymentMode: String!
    grandTotal: Float!
}

input UpdateAdminOrderProductInput {
   _id: ObjectId!
   paymentRemark: String
   paymentStatus: String
   shippingStatus: String
   shippedDate: Date
   deliveryDate: Date
   returnStatus: String
   returnUserReason: String
   returnAdminComment: String
   returnRequestDate: Date
   returnDate: Date
   returnRejectedDate: Date
   refundStatus: String
   refundAmount: Float
   refundRequestDate: Date
   refundDate: Date
   refundComment: String
   cancelUserReason: String
   cancelAdminComment: String
   cancelledDate: Date
   courierId: String
   invoiceNumber: String
}

input UpdateAdminOrderProductInMobileInput {
   _id: ObjectId!
   paymentRemark: String
   paymentStatus: String
   shippingStatus: String
   shippedDate: Date
   deliveryDate: Date
   returnStatus: String
   returnUserReason: String
   returnAdminComment: String
   returnRequestDate: Date
   returnDate: Date
   returnRejectedDate: Date
   refundStatus: String
   refundAmount: Float
   refundRequestDate: Date
   refundDate: Date
   refundComment: String
   cancelUserReason: String
   cancelAdminComment: String
   cancelledDate: Date
   courierId: String
   invoiceNumber: String
}

input ReturnUserOrderProductInput {
    _id: ObjectId!
    returnUserReason: String!
}

input ReturnUserOrderProductInMobileInput {
    _id: ObjectId!
    returnUserReason: String!
}

input CancelUserOrderProductInput {
    _id: ObjectId!
}

input CancelUserOrderProductInMobileInput {
    _id: ObjectId!
}

type CreateUserOrderResponse {
    orderId:String!
}

type CreateUserOrderInMobileResponse {
    orderId:String!
}

type UpdateAdminOrderProductResponse {
   _id: ObjectId
}
type UpdateAdminOrderProductInMobileResponse {
   _id: ObjectId
}

type ReturnUserOrderProductResponse {
   _id: ObjectId
}

type ReturnUserOrderProductInMobileResponse {
   _id: ObjectId
}
type CancelUserOrderProductResponse {
    _id: ObjectId
}
type CancelUserOrderProductResponse {
    _id: ObjectId
}

type CancelUserOrderProductInMobileResponse {
    _id: ObjectId
}


# User Order  Queries

type Query {
    getAdminOrders(input:GetAdminOrdersInput!): GetAdminOrdersResponse!
    getAdminOrderDetails(input:GetAdminOrderDetailsInput!): GetAdminOrderDetailsResponse!
    getAdminShippingProducts(input:GetAdminShippingProductsInput!): GetAdminShippingProductsResponse!
    getAdminReturnProducts(input:GetAdminReturnProductsInput!): GetAdminReturnProductsResponse!
    getAdminRefundProducts(input:GetAdminRefundProductsInput!): GetAdminRefundProductsResponse!
    getAdminOrderProduct(input:GetAdminOrderProductInput!): GetAdminOrderProductResponse!
    getAdminOrderProducts(input:GetAdminOrderProductsInput!): GetAdminOrderProductsResponse!


    getUserOrderProducts (input:GetUserOrderProductsInput!): GetUserOrderProductsResponse!
    getUserOrderProduct(input:GetUserOrderProductInput!): GetUserOrderProductResponse!
    getUserOrderDetails(input:GetUserOrderDetailsInput!): GetUserOrderDetailsResponse!

    # USER RELATED GET APIS IN MOBILE
    getUserOrderProductsInMobile (input:GetUserOrderProductsInMobileInput!): GetUserOrderProductsInMobileResponse!
    getUserOrderProductInMobile(input:GetUserOrderProductInMobileInput!): GetUserOrderProductInMobileResponse!
    getUserOrderDetailsInMobile(input:GetUserOrderDetailsInMobileInput!): GetUserOrderDetailsInMobileResponse!

    

    # VENDOR PORTAL ORDER RELATED GET APIS
    getVendorShippingProducts(input:GetVendorShippingProductsInput!): GetVendorShippingProductsResponse!
    getVendorReturnProducts(input:GetVendorReturnProductsInput!): GetVendorReturnProductsResponse!
    getVendorRefundProducts(input:GetVendorRefundProductsInput!): GetVendorRefundProductsResponse!
    getVendorOrderProduct(input:GetVendorOrderProductInput!): GetVendorOrderProductResponse!
    getVendorOrderProducts(input:GetVendorOrderProductsInput!): GetVendorOrderProductsResponse!
}


input GetAdminOrdersInput {
    _id: ObjectId
    userId: ObjectId
    vendorId: ObjectId
    orderId: String
    paymentMode: String
    orderStatus: String
    startDate: Date
    endDate: Date
    postCode: String
    page: Int
    size: Int
}

input GetAdminOrderDetailsInput {
    orderId: String!
}

input GetAdminShippingProductsInput {
    _id: ObjectId
    userId: ObjectId
    vendorId: ObjectId
    orderId: String
    productId: ObjectId
    itemId: String
    skuId: String
    paymentMode: String
    paymentStatus: String
    shippingStatus: String
    orderStartDate: Date
    orderEndDate: Date
    shippingStartDate: Date
    shippingEndDate: Date
    deliveryStartDate: Date
    deliveryEndDate: Date
    cancelledStartDate: Date
    cancelledEndDate: Date
    courierId: String
    invoiceNumber: String
    page: Int
    size: Int
    sort: String
}

input GetVendorShippingProductsInput {
    _id: ObjectId
    userId: ObjectId
    vendorId: ObjectId
    orderId: String
    productId: ObjectId
    itemId: String
    skuId: String
    paymentMode: String
    paymentStatus: String
    shippingStatus: String
    orderStartDate: Date
    orderEndDate: Date
    shippingStartDate: Date
    shippingEndDate: Date
    deliveryStartDate: Date
    deliveryEndDate: Date
    cancelledStartDate: Date
    cancelledEndDate: Date
    courierId: String
    invoiceNumber: String
    page: Int
    size: Int
    sort: String
}

input GetAdminReturnProductsInput {
    _id: ObjectId
    userId: ObjectId
    vendorId: ObjectId
    orderId: String
    productId: ObjectId
    itemId: String
    skuId: String
    paymentMode: String
    returnStatus: String
    deliveryStartDate: Date
    deliveryEndDate: Date
    returnRequestStartDate: Date
    returnRequestEndDate: Date
    returnStartDate: Date
    returnEndDate: Date
    returnRejectStartDate: Date
    returnRejectEndDate: Date
    courierId: String
    invoiceNumber: String
    page: Int
    size: Int
    sort: String
}

input GetVendorReturnProductsInput {
    _id: ObjectId
    userId: ObjectId
    vendorId: ObjectId
    orderId: String
    productId: ObjectId
    itemId: String
    skuId: String
    paymentMode: String
    returnStatus: String
    deliveryStartDate: Date
    deliveryEndDate: Date
    returnRequestStartDate: Date
    returnRequestEndDate: Date
    returnStartDate: Date
    returnEndDate: Date
    returnRejectStartDate: Date
    returnRejectEndDate: Date
    courierId: String
    invoiceNumber: String
    page: Int
    size: Int
    sort: String
}

input GetAdminRefundProductsInput {
    _id: ObjectId
    userId: ObjectId
    orderId: String
    itemId: String
    productId: ObjectId
    skuId: String
    paymentMode: String
    refundStatus: String
    refundRequestStartDate: Date
    refundRequestEndDate: Date
    refundStartDate: Date
    refundEndDate: Date
    courierId: String
    invoiceNumber: String
    page: Int
    size: Int
    sort: String
}

input GetVendorRefundProductsInput {
    _id: ObjectId
    userId: ObjectId
    orderId: String
    itemId: String
    productId: ObjectId
    skuId: String
    paymentMode: String
    refundStatus: String
    refundRequestStartDate: Date
    refundRequestEndDate: Date
    refundStartDate: Date
    refundEndDate: Date
    courierId: String
    invoiceNumber: String
    page: Int
    size: Int
    sort: String
}

input GetAdminOrderProductInput {
    _id: ObjectId!
}

input GetVendorOrderProductInput {
    _id: ObjectId!
}

input GetAdminOrderProductsInput {
    orderId: String!
}

input GetVendorOrderProductsInput {
    orderId: String!
}


input GetUserOrderProductInput {
    _id: ObjectId!
}

input GetUserOrderProductInMobileInput {
    _id: ObjectId!
}

input GetUserOrderDetailsInput {
    orderId: String!
}

input GetUserOrderDetailsInMobileInput {
    orderId: String!
}

input GetUserOrderProductsInput {
    page: Int
    size: Int
}

input GetUserOrderProductsInMobileInput {
    page: Int
    size: Int
}



type OrderShippingAddress {
    _id: ObjectId
    firstname: String
    email: String
    mobile: String
    streetName: String
    city: String
    houseNumber: String
    country: String
    postCode: String
    apartment: String
    suite: String
    unit: String
}

type OrderShippingAddressInMobile {
    _id: ObjectId
    firstname: String
    email: String
    mobile: String
    streetName: String
    city: String
    houseNumber: String
    country: String
    postCode: String
    apartment: String
    suite: String
    unit: String
}

type OrderPriceInfo {
    totalMRP: Float
    totalSellingPrice: Float
    totalShippingCharge: Float
    totalRefundAmount: Float
}


type AdminOrder {
    _id: ObjectId
    orderId: String
    userId: ObjectId
    vendorId: ObjectId
    paymentMode: String
    orderDate: Date
    orderStatus: String
    username: String
    shippingAddress: OrderShippingAddress
    orderPriceInfo: OrderPriceInfo
}

type FileData {
    fileType: String
    fileURL: String
    mimeType: String
    originalName: String
}



type UserOrderProduct {
    _id: ObjectId
    productId: ObjectId
    vendorId: ObjectId
    orderId: String
    itemId: String
    productName: String
    shortDescription: String
    skuId: String
    image: FileData
    returnPeriod: Int
    mrp: Float
    sellingPrice: Float
    shippingCharge: Float
    paymentMode: String
    paymentStatus: String
    orderDate: Date
    shippingStatus: String
    shippedDate: Date
    deliveryDate: Date
    returnStatus: String
    returnDate: Date
    returnRequestDate: Date
    returnRejectedDate: Date
    returnUserReason: String
    refundStatus: String
    refundAmount: Float
    refundDate: Date
    cancelledDate: Date
    cancelUserReason: String
    courierId: String
    invoiceNumber: String
    invoice: FileData
}

type UserOrderProductInMobile {
    _id: ObjectId
    productId: ObjectId
    vendorId: ObjectId
    orderId: String
    itemId: String
    productName: String
    shortDescription: String
    skuId: String
    image: FileData
    returnPeriod: Int
    mrp: Float
    sellingPrice: Float
    shippingCharge: Float
    paymentMode: String
    paymentStatus: String
    orderDate: Date
    shippingStatus: String
    shippedDate: Date
    deliveryDate: Date
    returnStatus: String
    returnDate: Date
    returnRequestDate: Date
    returnRejectedDate: Date
    returnUserReason: String
    refundStatus: String
    refundAmount: Float
    refundDate: Date
    cancelledDate: Date
    cancelUserReason: String
    courierId: String
    invoiceNumber: String
    invoice: FileData
}

type AdminOrderProduct {
    _id: ObjectId
    userId: ObjectId
    vendorId: ObjectId
    vendorName: String
    productId: ObjectId
    orderId: String
    itemId: String
    productName: String
    shortDescription: String
    skuId: String
    image: FileData
    returnPeriod: Int
    mrp: Float
    sellingPrice: Float
    shippingCharge: Float
    paymentMode: String
    paymentStatus: String
    paymentRemark: String
    orderDate: Date
    shippingStatus: String
    shippedDate: Date
    deliveryDate: Date
    returnStatus: String
    returnUserReason: String
    returnAdminComment: String
    returnRequestDate: Date
    returnRejectedDate: Date
    returnDate: Date
    refundStatus: String
    refundAmount: Float
    refundRequestDate: Date
    refundDate: Date
    refundComment: String
    cancelUserReason: String
    cancelAdminComment: String
    cancelledDate: Date
    courierId: String
    invoiceNumber: String
    invoice: FileData
    username: String
}

type VendorOrderProduct {
    _id: ObjectId
    userId: ObjectId
    vendorId: ObjectId
    productId: ObjectId
    orderId: String
    itemId: String
    productName: String
    shortDescription: String
    skuId: String
    image: FileData
    returnPeriod: Int
    mrp: Float
    sellingPrice: Float
    shippingCharge: Float
    paymentMode: String
    paymentStatus: String
    paymentRemark: String
    orderDate: Date
    shippingStatus: String
    shippedDate: Date
    deliveryDate: Date
    returnStatus: String
    returnUserReason: String
    returnAdminComment: String
    returnRequestDate: Date
    returnRejectedDate: Date
    returnDate: Date
    refundStatus: String
    refundAmount: Float
    refundRequestDate: Date
    refundDate: Date
    refundComment: String
    cancelUserReason: String
    cancelAdminComment: String
    cancelledDate: Date
    courierId: String
    invoiceNumber: String
    invoice: FileData
    username: String
}




type GetAdminOrdersResponse {
    maxRecords: Int!
    records: [AdminOrder]!
}


type GetAdminOrderDetailsResponse {
    _id: ObjectId
    orderId: String
    userId: ObjectId
    vendorId: ObjectId
    paymentMode: String
    orderDate: Date
    orderStatus: String
    username: String
    shippingAddress: OrderShippingAddress
    orderPriceInfo: OrderPriceInfo
}


type GetAdminShippingProductsResponse {
    maxRecords: Int!
    records: [AdminOrderProduct]!
}

type GetVendorShippingProductsResponse {
    maxRecords: Int!
    records: [VendorOrderProduct]!
}

type GetAdminReturnProductsResponse {
    maxRecords: Int!
    records: [AdminOrderProduct]!
}

type GetVendorReturnProductsResponse {
    maxRecords: Int!
    records: [VendorOrderProduct]!
}

type GetAdminRefundProductsResponse {
    maxRecords: Int!
    records: [AdminOrderProduct]!
}

type GetVendorRefundProductsResponse {
    maxRecords: Int!
    records: [VendorOrderProduct]!
}

type GetAdminOrderProductResponse {
     _id: ObjectId
    userId: ObjectId
    productId: ObjectId
    vendorId: ObjectId
    itemId: String
    orderId: String
    productName: String
    shortDescription: String
    skuId: String
    image: FileData
    returnPeriod: Int
    mrp: Float
    sellingPrice: Float
    shippingCharge: Float
    paymentMode: String
    paymentStatus: String
    paymentRemark: String
    orderDate: Date
    shippingStatus: String
    shippedDate: Date
    deliveryDate: Date
    returnStatus: String
    returnUserReason: String
    returnAdminComment: String
    returnRequestDate: Date
    returnRejectedDate: Date
    returnDate: Date
    refundStatus: String
    refundAmount: Float
    refundRequestDate: Date
    refundDate: Date
    refundComment: String
    cancelUserReason: String
    cancelAdminComment: String
    cancelledDate: Date
    courierId: String
    invoiceNumber: String
    invoice: FileData
}

type GetVendorOrderProductResponse {
     _id: ObjectId
    userId: ObjectId
    productId: ObjectId
    vendorId: ObjectId
    itemId: String
    orderId: String
    productName: String
    shortDescription: String
    skuId: String
    image: FileData
    returnPeriod: Int
    mrp: Float
    sellingPrice: Float
    shippingCharge: Float
    paymentMode: String
    paymentStatus: String
    paymentRemark: String
    orderDate: Date
    shippingStatus: String
    shippedDate: Date
    deliveryDate: Date
    returnStatus: String
    returnUserReason: String
    returnAdminComment: String
    returnRequestDate: Date
    returnRejectedDate: Date
    returnDate: Date
    refundStatus: String
    refundAmount: Float
    refundRequestDate: Date
    refundDate: Date
    refundComment: String
    cancelUserReason: String
    cancelAdminComment: String
    cancelledDate: Date
    courierId: String
    invoiceNumber: String
    invoice: FileData
}


type GetUserOrderProductsResponse {
    maxRecords: Int!
    records: [UserOrderProduct!]
}

type GetUserOrderProductsInMobileResponse {
    maxRecords: Int!
    records: [UserOrderProductInMobile!]
}


type GetAdminOrderProductsResponse {
    products: [AdminOrderProduct!]
}


type GetVendorOrderProductsResponse {
    products: [VendorOrderProduct!]
}


type GetUserOrderProductResponse {
    _id: ObjectId
    productId: ObjectId
    orderId: String
    vendorId: ObjectId
    itemId: String
    productName: String
    shortDescription: String
    skuId: String
    image: FileData
    returnPeriod: Int
    mrp: Float
    sellingPrice: Float
    shippingCharge: Float
    paymentMode: String
    paymentStatus: String
    orderDate: Date
    shippingStatus: String
    shippedDate: Date
    deliveryDate: Date
    returnStatus: String
    returnDate: Date
    returnRejectedDate: Date
    refundStatus: String
    refundAmount: Float
    refundDate: Date
    cancelledDate: Date
    courierId: String
    invoiceNumber: String
    invoice:FileData
}

type GetUserOrderProductInMobileResponse {
    _id: ObjectId
    productId: ObjectId
    orderId: String
    vendorId: ObjectId
    itemId: String
    productName: String
    shortDescription: String
    skuId: String
    image: FileData
    returnPeriod: Int
    mrp: Float
    sellingPrice: Float
    shippingCharge: Float
    paymentMode: String
    paymentStatus: String
    orderDate: Date
    shippingStatus: String
    shippedDate: Date
    deliveryDate: Date
    returnStatus: String
    returnDate: Date
    returnRejectedDate: Date
    refundStatus: String
    refundAmount: Float
    refundDate: Date
    cancelledDate: Date
    courierId: String
    invoiceNumber: String
    invoice:FileData
}


type GetUserOrderDetailsResponse {
     _id: ObjectId
    orderId: String
    paymentMode: String
    orderDate: Date
    orderStatus: String
    shippingAddress: OrderShippingAddress
}

type GetUserOrderDetailsInMobileResponse {
     _id: ObjectId
    orderId: String
    paymentMode: String
    orderDate: Date
    orderStatus: String
    shippingAddress: OrderShippingAddressInMobile
}


# Schema

schema {
    mutation: Mutation,
    query: Query
}


