scalar Upload

# Vendor auth Mutations

type Mutation {
  sendMobileOtp(input: sendMobileOtpInput!): sendMobileOtpResponse!
  verifyOtp(input: VerifyOtpInput!): VerifyOtpResponse!
  reSendMobileOtp(input: sendMobileOtpInput!): sendMobileOtpResponse!
}

# otp  Type

type MobileOtpData {
  code: String
  expiresAt: String
  mobileNumber: String
}

# otp Input

input sendMobileOtpInput {
  _id: String!
  mobileNumber: String!
}

# input MobileOtpDataInput {
#   code: String
#   expiresAt: String
# }

input VerifyOtpInput {
  _id: String!
  mobileOtp: String!
}

# otp Output

type sendMobileOtpResponse {
  _id: String
  message: String
}

# type Query {

# }


# Input 


# Schema

# Output
type VerifyOtpResponse {
  _id: String
  mobileNumber: String
  message: String
}

schema {
  mutation: Mutation
  # query: Query
}
