scalar Upload

# Vendor auth Mutations

type Mutation {
  sendVendorMobileOtp(input: sendVendorMobileOtpInput!): sendVendorMobileOtpResponse!
  verifyVendorOtp(input: VerifyVendorOtpInput!): VerifyVendorOtpResponse!
  reSendVendorMobileOtp(input: ReSendVendorMobileOtpInput!): ReSendVendorMobileOtpResponse!
}

# otp  Type

type MobileOtpData {
  code: String
  expiresAt: String
  mobileNumber: String
}


# otp Input

input sendVendorMobileOtpInput {
  fullName: String
  countryCode: String!
  mobileNumber: String!
}

input ReSendVendorMobileOtpInput {
  fullName: String
  countryCode: String!
  mobileNumber: String!
}


input VerifyVendorOtpInput {
  code: String!
}


# otp Output

type sendVendorMobileOtpResponse {
  _id: String
  message: String
}


type VerifyVendorOtpResponse {
  _id: String
  fullName: String
  countryCode: String
  mobileNumber: String
  message: String
}

type ReSendVendorMobileOtpResponse {
  _id: String
  message: String
}

# type Query {

# }


# Input 


# Output

schema {
  mutation: Mutation
  # query: Query
}
