scalar ObjectId
scalar Upload


type Mutation {
    createWarrantyPolicyBySuperAdmin(input:createWarrantyPolicyBySuperAdminInput!):createWarrantyPolicyBySuperAdminResponse
    updateWarrantyPolicyByAdmin(input:updateWarrantyPolicyByAdminInput):updateWarrantyPolicyByAdminResponse
    deleteWarrantyPolicyByAdmin(input:deleteWarrantyPolicyByAdminInput!):deleteWarrantyPolicyByAdminResponse
    updateStatusWarrantyPolicyByAdmin(input:updateStatusWarrantyPolicyByAdminInput!):updateStatusWarrantyPolicyByAdminResponse
  
}

type Query {


  getDefaultWarrantyPolicyInCategory(input:getDefaultWarrantyPolicyInCategoryInput):WarrantyPolicy!
  getAllWarrantyPoliciesBySuperAdmin(input:getAllWarrantyPoliciesBySuperAdminInput):getAllWarrantyPoliciesBySuperAdminResponse
  getWarrantyPolicyByAdmin(input:getWarrantyPolicyByAdminInput!):getWarrantyPolicyByAdminResponse
  getDefaultWarrantyPolicyInProduct(input:getDefaultWarrantyPolicyInProductInput):WarrantyPolicy!
 
}


input getDefaultWarrantyPolicyInProductInput{

       brandId:ObjectId
       categoryId:ObjectId


}

input getDefaultWarrantyPolicyInCategoryInput{

     id:ObjectId
   
}

input createWarrantyPolicyBySuperAdminInput{
    name: String!,
    description:String,
    warrantyType: [String!],
    duration: Int!,
}

input getAllWarrantyPoliciesBySuperAdminInput{
     page:Int
     size:Int
     search:String
     isEnable:Boolean
}

input getWarrantyPolicyByAdminInput{
    warrantyPolicyId:ObjectId!
}

input updateWarrantyPolicyByAdminInput{
  warrantyPolicyId:ObjectId!
  name:String
  description:String
  duration: Int
   warrantyType: [String],
}

input deleteWarrantyPolicyByAdminInput{
     warrantyPolicyId:ObjectId!
}

input updateStatusWarrantyPolicyByAdminInput{
   warrantyPolicyId:ObjectId!
   isEnable:Boolean!
}

type createWarrantyPolicyBySuperAdminResponse{
   success: Boolean,
   message: String,
}

type WarrantyPolicy{
     _id:ObjectId
    name:String
    description:String
    duration: Int
    isEnable:Boolean
    isDeleted:Boolean
    warrantyType:[String]
}

type getAllWarrantyPoliciesBySuperAdminResponse{
    success:Boolean
    data:[WarrantyPolicy]
    maxRecords:Int
}

type getWarrantyPolicyByAdminResponse{
     _id:ObjectId
    name:String
    description:String
    duration: Int
    isEnable:Boolean
    isDeleted:Boolean
    warrantyType:[String]
}

type updateWarrantyPolicyByAdminResponse{
   success: Boolean,
   message: String,
}

type deleteWarrantyPolicyByAdminResponse{
   success: Boolean,
   message: String,
}

type updateStatusWarrantyPolicyByAdminResponse{
    success: Boolean,
   message: String,
}
# Schema

schema {
  mutation: Mutation
  query: Query
}
