scalar ObjectId
scalar Upload


type Mutation {
   createReturnPolicyBySuperAdmin(input:createReturnPolicyBySuperAdminInput!):createReturnPolicyBySuperAdminResponse
}

type Query {
  getAllPoliciesBySuperAdmin(input:getAllPoliciesBySuperAdminInput):getAllPoliciesBySuperAdminResponse
}


input createReturnPolicyBySuperAdminInput {
     name:String!
     description:String
     duration: Int!
     conditions:[String]
}

input getAllPoliciesBySuperAdminInput{
     page:Int
     size:Int
     search:String
     isEnable:Boolean
}


type createReturnPolicyBySuperAdminResponse{
      success: Boolean,
      message: String,
}

type ReturnPolicy{
    _id:ObjectId
    name:String
    description:String
    duration: Int
    conditions:[String]
}

type getAllPoliciesBySuperAdminResponse {
   success:Boolean
    data:[ReturnPolicy]
    maxRecords:Int
}


# Schema

schema {
  mutation: Mutation
  query: Query
}
