scalar Upload
scalar ObjectId
scalar Date


# Update settings mutations

type Mutation {
    updatePaymentSettings(input: UpdatePaymentSettingsInput!): UpdatePaymentSettingsResponse!
    updateShippingSettings(input: UpdateShippingSettingsInput!): UpdateShippingSettingsResponse!
}

# Get settings  queries

type Query {
    getPaymentSettings: GetPaymentSettingsResponse!
    getShippingSettings: GetShippingSettingsResponse!
}



input UpdatePaymentSettingsInput {
    onlinePayment: Boolean
    cod: Boolean
}

input UpdateShippingSettingsInput {
    shippingCharge: Float
    freeShippingThreshold: Int 
    returnPeriod: Int
}

type UpdatePaymentSettingsResponse {
    onlinePayment: Boolean
    cod: Boolean
}

type UpdateShippingSettingsResponse{
    shippingCharge: Float
    freeShippingThreshold: Int 
    returnPeriod: Int
}

type GetPaymentSettingsResponse{
    onlinePayment: Boolean
    cod: Boolean
}

type GetShippingSettingsResponse {
    shippingCharge: Float
    freeShippingThreshold: Int 
    returnPeriod: Int
}




# Schema

schema {
    mutation: Mutation,
    query: Query
}


