  scalar Upload
  scalar ObjectId





# Admin auth Mutations

 type Mutation {
  createAdmin(input:createAdminInput!,image:Upload):createAdminResponse!
  createSuperAdmin(input: AdminSignUpInput!, image:Upload): AddAdminResponse!
  createSubAdmin(input: SubAdminSignUpInput!, image:Upload): AddAdminResponse!
  loginAdmin(input: AdminLoginInput!): AdminAuthResponse!
  updateAdminProfile(input: AdminEditProfileInput!, image:Upload): UpdateAdminResponse!
  adminApprovalForVendor(input: adminApprovalForVendorInput!): adminApprovalForVendorResponse!
  logoutAdmin:LogoutAdminResponse!
  cretaeDeliveryAgentConfig(input:cretaeDeliveryAgentConfigInput!):cretaeDeliveryAgentConfigResponse!
  updateDeliveryAgentConfig(input:updateDeliveryAgentConfigInput!):cretaeDeliveryAgentConfigResponse!
  suspendAdmin(input:suspendAdminInput!):suspendAdminResponse!
  deleteAdminAccount(input:suspendAdminInput!):suspendAdminResponse!
  editAdminAccount(input:editAdminAccountInput!,image:Upload):editAdminAccountResponse!
  
}



input editAdminAccountInput{
       
       id:ObjectId  
       fullName:String!
       email:String!
       accType:String!
       role:[ObjectId]
}

type editAdminAccountResponse{

      status:Boolean
      msg:String
}



type suspendAdminResponse{

     status:Boolean
     msg:String
}

input suspendAdminInput{

     id:ObjectId
     status:Boolean
}



 input createAdminInput{

       fullName:String!
       email:String!
       accType:String!
       password:String!
       role:[ObjectId]
}


type createAdminResponse{

    status:Boolean,
    msg:String
}




type getAllDeliveryAgentConfigResponse{
       _id:ObjectId,
       orderAssignLimit:Int
       returnOrderAssignLimit:Int
}


input updateDeliveryAgentConfigInput{
        _id:ObjectId!
        deliveryLimit:Int!
        returnLimit:Int!
}






input cretaeDeliveryAgentConfigInput{

       limit:Int
}


type cretaeDeliveryAgentConfigResponse{

       status:Boolean,
       msg:String
}






 type ImageData {
  fileType: String
  fileURL: String
  mimeType: String
  originalName: String
  }  


type  LogoutAdminResponse {
  message: String!
}


# Admin auth Type

type Admin {
  _id: String
  email: String
  password: String
  accType: String
  isBlocked: Boolean
  fullName: String
  profilePic: ImageData
}


# Admin auth Input

input AdminSignUpInput {
  email: String!
  password: String!
  fullName: String!
}

    
input SubAdminSignUpInput {
  email: String!
  password: String!
  isBlocked: Boolean!
  fullName: String!
}

input AdminLoginInput {
  email: String!
  password: String!
}

input AdminEditProfileInput {
  fullName: String
  email: String
  password: String
  isBlocked: Boolean
}

input adminApprovalForVendorInput {
  _id: String!
  isVerified: Boolean
}


# Admin auth Output

type AddAdminResponse {
  _id: String!
}

type AdminAuthResponse {
  _id: String
  token: String
}

type UpdateAdminResponse {
    _id: String
    message:String
}

type Query {
    getAdminRecord: getAdminRecordResponse
    getAllDeliveryAgentConfig:getAllDeliveryAgentConfigResponse!
    getAllAdminData(input:getAllAdminDataInput):getAllAdminDataResponse!
    getOneAdminDetails(input:getOneAdminDetailsInput):getOneAdminDetailsResponse!
}


input getAllAdminDataInput{
      
      page:Int
      size:Int
      isBlocked:String
      search:String

}


input getOneAdminDetailsInput{

     _id:ObjectId
}


type getOneAdminDetailsResponse{

     _id: String
  fullName: String
  email: String
  accType: String
  isBlocked: Boolean
  roles:[adminroles]

}

 type adminroles {
    _id:ObjectId
    name:String
    description:String
    permissions:[String]
    isEnable:Boolean
}


type getAllAdminDataResponse{

     records:[getAllAdminDataType]
     maxRecords:Int

}

type getAllAdminDataType{

  _id: String
  fullName: String
  email: String
  accType: String
  isBlocked: Boolean
 
  
}






type getAdminRecordResponse{
   record: Admin
}

type adminApprovalForVendorResponse {
  _id: String
  message: String
}


# Schema

schema {
mutation: Mutation,
query: Query
}


