scalar ObjectId

# wishList Mutations

type Mutation {
  addToWishList(input: AddToWishListInput!): AddToWishListResponse!
  removeFromWishList(input: RemoveFromWishListInput!):RemoveFromWishListResponse!

  #  Mobile 
    addToMobileWishList(input: AddToMobileWishListInput!): AddToMobileWishListResponse!
    removeFromMobileWishList(input: RemoveFromMobileWishListInput!):RemoveFromMobileWishListResponse!
}

type Query{
  getWishListProducts:GetWishListProductsResponse!
  getWishListProductStatus(input: GetWishListProductStatusInput!):GetWishListProductStatusResponse!

  # Mobile
  getMobileWishListProducts:GetMobileWishListProductsResponse!
  getMobileWishListProductStatus(input: GetMobileWishListProductStatusInput!):GetMobileWishListProductStatusResponse!
}


# wishList Input

input AddToWishListInput {
  productId:ObjectId!
}
input RemoveFromWishListInput {
  productId:ObjectId!
}

input GetWishListProductStatusInput {
  productId: ObjectId!
}

input AddToMobileWishListInput {
  productId:ObjectId!
}
input RemoveFromMobileWishListInput {
  productId:ObjectId!
}

input GetMobileWishListProductStatusInput {
  productId: ObjectId!
}


# wishList Output

type AddToWishListResponse {
  message:String
}
type RemoveFromWishListResponse {
  message:String
}

type AddToMobileWishListResponse {
  message:String
}
type RemoveFromMobileWishListResponse {
  message:String
}



type WishListProduct {
  productId: ObjectId!
  productName: String!
  shortDescription: String
  sellingPrice: Float!
  image: String
}


type GetWishListProductsResponse {
  products:[WishListProduct]
}

type GetWishListProductStatusResponse {
  isExist:Boolean!
}


type GetMobileWishListProductsResponse {
  products:[WishListProduct]
}

type GetMobileWishListProductStatusResponse {
  isExist:Boolean!
}



# Schema

schema {
  mutation: Mutation,
  query: Query
}


