scalar ObjectId

# wishList Mutations

type Mutation {
  addToWishList(input: AddToWishListInput!): AddToWishListResponse!
  removeFromWishList(input: RemoveFromWishListInput!):RemoveFromWishListResponse!
}

type Query{
  getWishListProducts:GetWishListProductsResponse!
  getWishListProductStatus(input: GetWishListProductStatusInput!):GetWishListProductStatusResponse!
}


# wishList Input

input AddToWishListInput {
  productId:ObjectId!
}
input RemoveFromWishListInput {
  productId:ObjectId!
}

input GetWishListProductStatusInput {
  productId: ObjectId!
}

# wishList Output

type AddToWishListResponse {
  message:String
}
type RemoveFromWishListResponse {
  message:String
}



type WishListProduct {
  productId: ObjectId!
  productName: String!
  shortDescription: String
  sellingPrice: Float!
  image: String
}


type GetWishListProductsResponse {
  products:[WishListProduct]
}

type GetWishListProductStatusResponse {
  isExist:Boolean!
}

# Schema

schema {
  mutation: Mutation,
  query: Query
}


