scalar ObjectId
scalar Date




input GetDashboardUsersGraphInput {
    startDate: Date
    endDate: Date
    graphType: String
}

input GetDashboardVendorsGraphInput {
    startDate: Date
    endDate: Date
    graphType: String
}



input GetDashboardOrdersGraphInput {
    startDate: Date
    endDate: Date
    graphType: String
    vendorId: ObjectId
}

input GetVendorDashboardOrdersGraphInput {
    startDate: Date
    endDate: Date
    graphType: String
}



input GetDashboardOrdersPieChartDataInput {
    startDate: Date
    endDate: Date
    vendorId: ObjectId
}
input GetVendorDashboardOrdersPieChartDataInput {
    startDate: Date
    endDate: Date
}

input GetDashboardReturnedOrdersPieChartDataInput {
    startDate: Date
    endDate: Date
    vendorId: ObjectId
}
input GetVendorDashboardReturnedOrdersPieChartDataInput {
    startDate: Date
    endDate: Date
}

input GetDashboardRefundOrdersPieChartDataInput {
    startDate: Date
    endDate: Date
    vendorId: ObjectId
}

input GetVendorDashboardRefundOrdersPieChartDataInput {
    startDate: Date
    endDate: Date
}

input GetDashboardOrdersAmountPieChartDataInput{
    startDate: Date
    endDate: Date
    vendorId: ObjectId
}
input GetVendorDashboardOrdersAmountPieChartDataInput{
    startDate: Date
    endDate: Date
}

input GetDashboardShippingChargePieChartDataInput{
    startDate: Date
    endDate: Date
    vendorId: ObjectId
}
input GetVendorDashboardShippingChargePieChartDataInput{
    startDate: Date
    endDate: Date
}

input GetDashboardOrderSummaryInput {
    vendorId: ObjectId
}

input GetDashboardReturnedOrderSummaryInput {
    vendorId: ObjectId
}

input getDashboardRefundOrdersSummaryInput {
    vendorId: ObjectId
}

type GetDashboardUsersSummaryResponse {
    totalUsers: Int 
    activeUsers: Int
    blockedUsers: Int
    todayUsers: Int
    weekUsers: Int
    monthUsers:Int
    yearUsers:Int
}

type GetDashboardVendorsSummaryResponse {
    totalVendors: Int 
    activeVendors: Int
    blockedVendors: Int
    todayVendors: Int
    weekVendors: Int
    monthVendors:Int
    yearVendors:Int
}

type GetDashboardUsersGraphResposne {
    y1:[Int],
    x:[String]
}

type GetDashboardVendorsGraphResposne {
    y1:[Int],
    x:[String]
}


type GetDashboardOrderSummaryResponse{
    pendingOrders: Int
    progressOrders: Int
    shippedOrders: Int
    deliveredOrders: Int
    cancelledOrders: Int
    returnedOrders: Int 
}
type GetVendorDashboardOrderSummaryResponse{
    pendingOrders: Int
    progressOrders: Int
    shippedOrders: Int
    deliveredOrders: Int
    cancelledOrders: Int
    returnedOrders: Int 
}


type GetDashboardOrdersGraphResposne {
    y1:[Int],
    x:[String]
}
type GetVendorDashboardOrdersGraphResposne {
    y1:[Int],
    x:[String]
}

type GetDashboardOrdersPieChartDataResponse {
    deliveredOrders: Int
    cancelledOrders:Int
    returnedOrders: Int
}
type GetVendorDashboardOrdersPieChartDataResponse {
    deliveredOrders: Int
    cancelledOrders:Int
    returnedOrders: Int
}


type GetDashboardReturnedOrdersPieChartDataResponse{
    pending: Int
    approved:Int
    rejected: Int
}


type GetDashboardReturnedOrderSummaryResponse{
    pending: Int
    approvedToday: Int
    rejectedToday: Int
}


type GetDashboardRefundOrdersPieChartDataResponse{
    pending: Float
    paid:Float
}


type GetDashboardRefundOrderSummaryResponse{
    pendingAmount: Int
    paidToday: Int
}

type GetDashboardOrdersAmountPieChartDataResponse{
    pending: Float
    paid:Float
}

type GetDashboardShippingChargePieChartDataResponse{
    pending: Float
    paid:Float
}



# Mutations

# type Mutation {
# }



# Queries

type Query {
    getDashboardUsersSummary:GetDashboardUsersSummaryResponse!
    getDashboardUsersGraph(input:GetDashboardUsersGraphInput!): GetDashboardUsersGraphResposne!
    getDashboardVendorsSummary:GetDashboardVendorsSummaryResponse!
    getDashboardVendorsGraph(input:GetDashboardVendorsGraphInput!): GetDashboardVendorsGraphResposne!
    
    getDashboardOrderSummary(input: GetDashboardOrderSummaryInput!):GetDashboardOrderSummaryResponse!
    getDashboardOrdersGraph(input:GetDashboardOrdersGraphInput!): GetDashboardOrdersGraphResposne!
    getDashboardOrdersPieChartData(input:GetDashboardOrdersPieChartDataInput!):GetDashboardOrdersPieChartDataResponse!
    getDashboardReturnedOrdersPieChartData(input:GetDashboardReturnedOrdersPieChartDataInput!):GetDashboardReturnedOrdersPieChartDataResponse!
    getDashboardReturnedOrderSummary(input: GetDashboardReturnedOrderSummaryInput!):GetDashboardReturnedOrderSummaryResponse!
    getDashboardRefundOrdersPieChartData(input:GetDashboardRefundOrdersPieChartDataInput!):GetDashboardRefundOrdersPieChartDataResponse!
    getDashboardRefundOrdersSummary(input:getDashboardRefundOrdersSummaryInput!):GetDashboardRefundOrderSummaryResponse!
    getDashboardOrdersAmountPieChartData(input:GetDashboardOrdersAmountPieChartDataInput!):GetDashboardOrdersAmountPieChartDataResponse!
    getDashboardShippingChargePieChartData(input:GetDashboardShippingChargePieChartDataInput!):GetDashboardShippingChargePieChartDataResponse!

    getVendorDashboardOrderSummary:GetVendorDashboardOrderSummaryResponse!
    getVendorDashboardOrdersGraph(input:GetVendorDashboardOrdersGraphInput!): GetVendorDashboardOrdersGraphResposne!
    getVendorDashboardOrdersPieChartData(input:GetVendorDashboardOrdersPieChartDataInput!):GetVendorDashboardOrdersPieChartDataResponse!
    getVendorDashboardReturnedOrdersPieChartData(input: GetVendorDashboardReturnedOrdersPieChartDataInput!):GetDashboardReturnedOrdersPieChartDataResponse!
    getVendorDashboardReturnedOrderSummary:GetDashboardReturnedOrderSummaryResponse!
    getVendorDashboardRefundOrdersPieChartData(input:GetVendorDashboardRefundOrdersPieChartDataInput!):GetDashboardRefundOrdersPieChartDataResponse!
    getVendorDashboardRefundOrdersSummary:GetDashboardRefundOrderSummaryResponse!

    getVendorDashboardOrdersAmountPieChartData(input:GetVendorDashboardOrdersAmountPieChartDataInput!):GetDashboardOrdersAmountPieChartDataResponse!
    getVendorDashboardShippingChargePieChartData(input:GetVendorDashboardShippingChargePieChartDataInput!):GetDashboardShippingChargePieChartDataResponse!

}




# Schema


schema {
# mutation: Mutation,
query: Query
}