scalar ObjectId

# user auth Mutations

 type Mutation {
  userLoginOtp(input: userLoginOtpInput!): userLoginOtpResponse!
  userVerifyOtp(input:userVerifyOtpInput!): userVerifyOtpResponse!
  userBlock(input:userBlockInput!):userBlockResponse!
  updateUserProfile(input:updateUserProfileInput!):updateUserProfileResponse!
  updateUserProfileByAdmin(input:UpdateUserProfileByAdminInput!):UpdateUserProfileByAdminResponse!
  logoutUser:UserLogoutResponse!
  accountDeleteByUser(input:accountDeleteByUserInput!):accountDeleteByUserResponse!

  # Mobile API
    userLoginOtpInMobile(input: userLoginOtpInMobileInput!): userLoginOtpInMobileResponse!
    userVerifyOtpInMobile(input:userVerifyOtpInMobileInput!): userVerifyOtpInMobileResponse!
    updateUserProfileInMobile(input:updateUserProfileInMobileInput!):updateUserProfileInMobileResponse!
    logoutMobileUser:LogoutMobileUserResponse!

}

# user auth query

type Query{
  getUsersByAdmin(input:userFilters):usersResponse!
  getUserRecordByAdmin(input:userInput!):userResponse!
  getUserRecord:GetUserRecordResponse!

  # Mobile API
  getUserRecordInMobile:GetUserRecordInMobileResponse!
}
                  
# user auth Input

input accountDeleteByUserInput{
   isDeleted:Boolean!
   deleteReason:String
}

type accountDeleteByUserResponse{
  success:Boolean
  message:String
}

input userLoginOtpInput {
  mobileNumber: String!
  countryCode:String!
}

input userLoginOtpInMobileInput {
  mobileNumber: String!
  countryCode:String!

}

input userBlockInput {
  _id: String!
  isBlocked:Boolean!
}

input userFilters{
  page: Int
  size: Int
  isBlocked:Boolean
  isDeleted:Boolean
  query: String
}

input userVerifyOtpInput {
  code: String!
  _id: ObjectId!
}

input userVerifyOtpInMobileInput {
  code: String!
  _id: ObjectId!
}


input updateUserProfileInput {
  email: String
  firstName: String
  lastName: String
  displayName: String
}

input UpdateUserProfileByAdminInput {
  _id: ObjectId
  email: String
  firstName: String
  lastName: String
  displayName: String
  mobileNumber: String
  isBlocked: Boolean
}

input updateUserProfileInMobileInput {
  email: String
  firstName: String
  lastName: String
  displayName: String
}


input userInput{
  _id: String!
} 

# user auth Output

type userBlockResponse{
  message:String
}

type userLoginOtpResponse {
  message: String!
  mobileNumber:String!
  _id: ObjectId!
  }

type userLoginOtpInMobileResponse {
  message: String!
  mobileNumber:String!
  _id: ObjectId!
  }

type userVerifyOtpResponse {
  userId: String
  token: String
  message:String
  }

 type userVerifyOtpInMobileResponse {
  userId: String
  token: String
  message:String
  } 
type userSignUpResponse {
    _id: String
    message: String
    token: String
  }

type user{
  _id:String
  email: String
  firstName: String
  lastName: String
  displayName: String
  mobileNumber: String
  isBlocked: Boolean
  isDeleted:Boolean
}

type usersResponse {
    maxRecords: Int!
    records: [user!]
}

type updateUserProfileResponse {
   message: String
}

type UpdateUserProfileByAdminResponse {
   message: String
}


type updateUserProfileInMobileResponse {
   message: String
}

type userResponse{
  record: user
  message: String
}

type userInMobileResponse{
  record: user
  message: String
}
  

type UserLogoutResponse {
  _id: ObjectId!
}

type LogoutMobileUserResponse {
  _id: ObjectId!
}


type GetUserRecordResponse {
  record: user
  message: String
}

type GetUserRecordInMobileResponse {
  record: user
  message: String
}



# Schema

schema {
mutation: Mutation,
query: Query
}

