scalar ObjectId

# user auth Mutations

 type Mutation {
  userLoginOtp(input: userLoginOtpInput!): userLoginOtpResponse!
  userResendLoginOtp(input: userResendLoginOtpInput!): userResendLoginOtpResponse!
  userVerifyOtp(input:userVerifyOtpInput!): userVerifyOtpResponse!
  userBlock(input:userBlockInput!):userBlockResponse!
  updateUserProfile(input:updateUserProfileInput!):updateUserProfileResponse!

  # Mobile API
    userLoginOtpInMobile(input: userLoginOtpInMobileInput!): userLoginOtpInMobileResponse!
    userVerifyOtpInMobile(input:userVerifyOtpInMobileInput!): userVerifyOtpInMobileResponse!
    updateUserProfileInMobile(input:updateUserProfileInMobileInput!):updateUserProfileInMobileResponse!
}

# user auth query

type Query{
  getUsersByAdmin(input:userFilters):usersResponse!
  getUserRecordByAdmin(input:userInput!):userResponse!
  getUserRecord(input:userInput!):userResponse!

  # Mobile API
  getUserRecordInMobile(input:userInMobileInput!):userInMobileResponse!
}

# user auth Input

input userLoginOtpInput {
  mobileNumber: String!
}

input userResendLoginOtpInput {
  mobileNumber: String!
}

input userLoginOtpInMobileInput {
  mobileNumber: String!
}

input userBlockInput {
  _id: String!
  isBlocked:Boolean!
}

input userFilters{
  page: Int
  size: Int
  isBlocked:Boolean
  query: String
}

input userVerifyOtpInput {
  code: String!
  _id: ObjectId!
}

input userVerifyOtpInMobileInput {
  code: String!
  _id: ObjectId!
}


input updateUserProfileInput {
  email: String
  firstName: String
  lastName: String
  displayName: String

  mobileNumber: String
  isBlocked: Boolean
}

input updateUserProfileInMobileInput {
  email: String
  firstName: String
  lastName: String
  displayName: String
  mobileNumber: String
  isBlocked: Boolean
}


input userInput{
  _id: String!
} 

input userInMobileInput{
  _id: String!
} 

# user auth Output

type userBlockResponse{
  message:String
}

type userLoginOtpResponse {
  message: String!
  mobileNumber:String!
  _id: ObjectId!
  }

  type userResendLoginOtpResponse {
  message: String!
  mobileNumber:String!
  }

type userLoginOtpInMobileResponse {
  message: String!
  mobileNumber:String!
  _id: ObjectId!
  }

type userVerifyOtpResponse {
  userId: String
  token: String
  message:String
  }

 type userVerifyOtpInMobileResponse {
  userId: String
  token: String
  message:String
  } 
type userSignUpResponse {
    _id: String
    message: String
    token: String
  }

type user{
  _id:String
  email: String
  firstName: String
  lastName: String
  displayName: String
  mobileNumber: String
  isBlocked: Boolean
}

type usersResponse {
    maxRecords: Int!
    records: [user!]
}

type updateUserProfileResponse {
   message: String
}

type updateUserProfileInMobileResponse {
   message: String
}

type userResponse{
  record: user
  message: String
}

type userInMobileResponse{
  record: user
  message: String
}
  
# Schema

schema {
mutation: Mutation,
}


