scalar Upload
scalar ObjectId


# User Shipping Address  Mutations

type Mutation {
    createUserShippingAddress(input: UserCreateShippingAddressInput!): UserCreateShippingAddressResponse!
    editUserShippingAddress(input: UserEditShippingAddressInput!): UserEditShippingAddressResponse!
    removeUserShippingAddress(input: UserRemoveShippingAddressInput!): UserRemoveShippingAddressResponse!
    updateUserShippingAddressAsDefault(input: updateUserShippingAddressAsDefaultInput!): updateUserShippingAddressAsDefaultResponse!

    # Mobile
    createMobileUserShippingAddress(input: CreateMobileUserShippingAddressInput!): CreateMobileUserShippingAddressResponse!
    editMobileUserShippingAddress(input: EditMobileUserShippingAddressInput!): EditMobileUserShippingAddressResponse!
    removeMobileUserShippingAddress(input: RemoveMobileUserShippingAddressInput!): RemoveMobileUserShippingAddressResponse!
    updateMobileUserShippingAddressAsDefault(input: UpdateMobileUserShippingAddressAsDefaultInput!): UpdateMobileUserShippingAddressAsDefaultResponse!
}


# Shipping Address Input

input UserCreateShippingAddressInput {
    firstname: String!
    email: String
    mobile: String!
    streetName: String!
    city: String!
    houseNumber: String!
    country: String
    postCode: String!
    apartment: String
    suite: String
    unit: String
    governorate:String!
    village:String!
    isDefault: Boolean
}

input CreateMobileUserShippingAddressInput {
    firstname: String!
    email: String
    mobile: String!
    streetName: String!
    city: String!
    houseNumber: String!
    country: String
    postCode: String!
    apartment: String
    suite: String
    unit: String
    isDefault: Boolean
}


# Shipping Address Edit Input

input UserEditShippingAddressInput {
    _id: ObjectId!
    firstname: String
    email: String
    mobile: String
    streetName: String
    city: String
    apartment: String
    suite: String
    unit: String
    postCode: String
    houseNumber: String
    country: String
    governorate:String
    village:String
 
}

input EditMobileUserShippingAddressInput {
    _id: ObjectId!
    firstname: String
    email: String
    mobile: String
    streetName: String
    city: String
    apartment: String
    suite: String
    unit: String
    postCode: String
    houseNumber: String
    country: String
 
}


# Shipping Address Remove Input

input UserRemoveShippingAddressInput {
    _id: ObjectId!
}


input RemoveMobileUserShippingAddressInput {
    _id: ObjectId!
}


# Shipping Address set as default Input

input updateUserShippingAddressAsDefaultInput {
    addressId: ObjectId!
}

input UpdateMobileUserShippingAddressAsDefaultInput {
    addressId: ObjectId!
}

# Shipping Address Create Output

type UserCreateShippingAddressResponse {
    _id: ObjectId!
}

type CreateMobileUserShippingAddressResponse {
    _id: ObjectId!
}

# Shipping Address Edit Output

type UserEditShippingAddressResponse {
    _id: ObjectId!
}

type EditMobileUserShippingAddressResponse {
    _id: ObjectId!
}


# Shipping Address Remove Output

type UserRemoveShippingAddressResponse {
    _id: ObjectId!
    message: String
}

type RemoveMobileUserShippingAddressResponse {
    _id: ObjectId!
    message: String
}

# set as default response
type updateUserShippingAddressAsDefaultResponse {
    _id: ObjectId!
    message: String
}


type UpdateMobileUserShippingAddressAsDefaultResponse {
    _id: ObjectId!
    message: String
}

# User Shipping Address  Queries

type Query {
    getUserShippingAddresses: GetUserShippingAddressesResponse!
    getUserShippingAddress(input:GetUserShippingAddressInput!): GetUserShippingAddressResponse!
    getUserDefaultShippingAddress: GetUserShippingAddressResponse!

    # mobile
    getMobileUserShippingAddresses: GetMobileUserShippingAddressesResponse!
    getMobileUserShippingAddress(input:GetMobileUserShippingAddressInput!): GetMobileUserShippingAddressResponse!
    getMobileUserDefaultShippingAddress: GetMobileUserDefaultShippingAddressResponse!


}


input GetUserShippingAddressInput {
    _id: ObjectId!  
}

input GetMobileUserShippingAddressInput {
    _id: ObjectId!  
}

type UserShippingAddress {
    _id: ObjectId 
    firstname: String
    email: String
    mobile: String
    streetName: String
    city: String
    apartment: String
    suite: String
    unit: String
    postCode: String
    houseNumber: String
    country: String
    governorate:String
    village:String
    isDefault: Boolean
}

type GetUserShippingAddressesResponse {
    address:[UserShippingAddress]
}


type GetMobileUserShippingAddressesResponse {
    address:[UserShippingAddress]
}

type GetUserShippingAddressResponse {
    _id: ObjectId
    firstname: String
    email: String
    mobile: String
    streetName: String
    city: String
    apartment: String
    suite: String
    unit: String
    postCode: String
    houseNumber: String
    country: String
    governorate:String
    village:String
    isDefault: Boolean
}


type GetMobileUserShippingAddressResponse {
    _id: ObjectId
    firstname: String
    email: String
    mobile: String
    streetName: String
    city: String
    apartment: String
    suite: String
    unit: String
    postCode: String
    houseNumber: String
    country: String
    isDefault: Boolean
}



type GetMobileUserDefaultShippingAddressResponse {
    _id: ObjectId
    firstname: String
    email: String
    mobile: String
    streetName: String
    city: String
    apartment: String
    suite: String
    unit: String
    postCode: String
    houseNumber: String
    country: String
    isDefault: Boolean
}

# Schema

schema {
    mutation: Mutation,
    query: Query
}


