scalar Upload
scalar ObjectId


# User Shipping Address  Mutations

type Mutation {
    createUserShippingAddress(input: UserCreateShippingAddressInput!): UserCreateShippingAddressResponse!
    editUserShippingAddress(input: UserEditShippingAddressInput!): UserEditShippingAddressResponse!
    removeUserShippingAddress(input: UserRemoveShippingAddressInput!): UserRemoveShippingAddressResponse!
    updateUserShippingAddressAsDefault(input: updateUserShippingAddressAsDefaultInput!): updateUserShippingAddressAsDefaultResponse!
}


# Shipping Address Input

input UserCreateShippingAddressInput {
    firstname: String!
    email: String
    mobile: String!
    streetName: String!
    city: String!
    houseNumber: String!
    country: String
    postCode: String!
    apartment: String
    suite: String
    unit: String
    isDefault: Boolean
}

# Shipping Address Edit Input

input UserEditShippingAddressInput {
    _id: ObjectId!
    firstname: String
    email: String
    mobile: String
    streetName: String
    city: String
    apartment: String
    suite: String
    unit: String
    postCode: String
    houseNumber: String
    country: String
 
}

# Shipping Address Remove Input

input UserRemoveShippingAddressInput {
    _id: ObjectId!
}

# Shipping Address set as default Input

input updateUserShippingAddressAsDefaultInput {
    addressId: ObjectId!
}

# Shipping Address Create Output

type UserCreateShippingAddressResponse {
    _id: ObjectId!
}

# Shipping Address Edit Output

type UserEditShippingAddressResponse {
    _id: ObjectId!
}


# Shipping Address Remove Output

type UserRemoveShippingAddressResponse {
    _id: ObjectId!
    message: String
}

# set as default response
type updateUserShippingAddressAsDefaultResponse {
    _id: ObjectId!
    message: String
}

# User Shipping Address  Queries

type Query {
    getUserShippingAddresses: GetUserShippingAddressesResponse!
    getUserShippingAddress(input:GetUserShippingAddressInput!): GetUserShippingAddressResponse!
    getUserDefaultShippingAddress: GetUserShippingAddressResponse!

}


input GetUserShippingAddressInput {
    _id: ObjectId!  
}

type UserShippingAddress {
    _id: ObjectId 
    firstname: String
    email: String
    mobile: String
    streetName: String
    city: String
    apartment: String
    suite: String
    unit: String
    postCode: String
    houseNumber: String
    country: String
    isDefault: Boolean
}

type GetUserShippingAddressesResponse {
    address:[UserShippingAddress]
}

type GetUserShippingAddressResponse {
    _id: ObjectId
    firstname: String
    email: String
    mobile: String
    streetName: String
    city: String
    apartment: String
    suite: String
    unit: String
    postCode: String
    houseNumber: String
    country: String
    isDefault: Boolean
}



# Schema

schema {
    mutation: Mutation,
    query: Query
}


