scalar ObjectId


# cart Mutations

 type Mutation {
  addToCart(input: addToCartInput!): addToCartResponse!
  removeFromCart(input: removeFromCartInput!):removeFromCartResponse!
  updateCartQuantity(input: updateCartQuantityInput!):updateCartQuantityResponse!
  bulkAddToCart(input: BulkAddToCartInput!): BulkAddToCartResponse!
  # MOBILE SIDE APIS
    addToCartInMobile(input: addToCartInMobileInput!): addToCartInMObileResponse!
    removeFromCartInMobile(input: removeFromCartInMobileInput!):removeFromCartInMobileResponse!
    updateCartQuantityInMobile(input: updateCartQuantityInMobileInput!):updateCartQuantityInMobileResponse!
}

# cart query
 type Query{
  getCart:getCartResponse!
  getCartInMobile:getCartInMobileResponse!
 }

# cart Input


input addToCartInput {
    productId:ObjectId!
    quantity:Int!
}

input addToCartInMobileInput {
    productId:ObjectId!
    quantity:Int!
}
input removeFromCartInput {
    productId:String!
}
input removeFromCartInMobileInput {
    productId:String!
}
input updateCartQuantityInput {
    productId:String!
    quantity:Int!
}
input updateCartQuantityInMobileInput {
    productId:String!
    quantity:Int!
}

input CartItem {
  productId:ObjectId!
  quantity:Int!  
}

input BulkAddToCartInput {
  products: [CartItem!]
}

# cart Output

type addToCartResponse{
  message:String
}
type BulkAddToCartResponse{
  message:String
}
type addToCartInMObileResponse{
  message:String
}
type removeFromCartResponse{
  message:String
}
type removeFromCartInMobileResponse{
  message:String
}
type updateCartQuantityResponse{
  message:String
}
type updateCartQuantityInMobileResponse{
  message:String
}


type cartProduct{
    _id: ObjectId
    productId: ObjectId
    quantity:Int
    name: String
    shortDescription: String
    stock: Int
    color: String
    size: String
    price: Float
    image: String
    sellingPrice: Float
    mrp: Float
}

type getCartResponse{
  products:[cartProduct]
  grandTotal:Int
  subTotal:Int
  deliveryCharge:Int
}

type getCartInMobileResponse{
  products:[cartProduct]
  grandTotal:Int
  subTotal:Int
  deliveryCharge:Int
}


# Schema

schema {
mutation: Mutation,
}


