scalar ObjectId


# cart Mutations

 type Mutation {
  addToCart(input: addToCartInput!): addToCartResponse!
  removeFromCart(input: removeFromCartInput!):removeFromCartResponse!
  updateCartQuantity(input: updateCartQuantityInput!):updateCartQuantityResponse!
  
}

# cart query
 type Query{
  getCart:getCartResponse!
 }

# cart Input

input addToCartInput {
    productId:ObjectId!
    quantity:Int!
}
input removeFromCartInput {
    productId:String!
}
input updateCartQuantityInput {
    productId:String!
    quantity:Int!
}

# cart Output

type addToCartResponse{
  message:String
}
type removeFromCartResponse{
  message:String
}
type updateCartQuantityResponse{
  message:String
}





type cartProduct{
    _id: ObjectId
    productId: ObjectId
    quantity:Int
    name: String
    shortDescription: String
    stock: Int
    color: String
    size: String
    price: Float
    image: String
    sellingPrice: Float
    mrp: Float
}

type getCartResponse{
  products:[cartProduct]
  grandTotal:Int
  subTotal:Int
  deliveryCharge:Int
}


# Schema

schema {
mutation: Mutation,
}


