import { Schema, model } from "mongoose";
import argon2 from "argon2";
import { collections } from "../configs";
import { IDeliveryAgentDocument } from "src/services/deliveryAgentService";

const fileSchema = new Schema(
  {
      fileType: {
          type: String,
          enum: ["PRIVATE", "PUBLIC"],
          default: "PUBLIC",
          required: true
      },
      fileURL: {
          type: String,
          required: true
      },
      mimeType: {
          type: String,
          required: true
      },
      originalName: {
          type: String,
          required: true
      }
  },
  {
      _id: true,
      timestamps: true
  }
);

const deliveryAgentSchema = new Schema(
    {
        fullName: {
            type: String,
            required: true,
          },
          contactNumber: {
            type: String,
            required: true,
          },
          userID: {              //this is email
            type: String,
            unique: true,
            required: true,
            sparse: true,
            lowercase: true,
          },
          ID:{                     // this is unique id of agent generated by admin 
            type: String,
            unique: true,
            required: true,
          },
          licence:fileSchema,
          password: {
            type: String,
            required: true,
          },
          agentType: {
            type: String,
            enum: ['ArabDeals', 'Vendor', 'ThirdParty'],
            required: true,
          },
          isActive: {
            type: Boolean,
            default: true,                     // true = active, false = suspended
          },
          vendorID: {
            type: Schema.Types.ObjectId,
            ref: collections.VENDORS, 
            default: null
          },
          wallet:{
            cashInHand:  {                    //balance  amount agent has in his wallet
              type: Number, 
              default:0 
            },
            lastSettlementDate:  { 
              type: Date 
            },
            grandTotal: {       
              type: Number,  
              default:0 
            },
            totalSettlement: {                  //total amount agent has settled
              type: Number, 
              default:0 
            },
            numberOfOrderAssigned:{
              type: Number, 
            },
            numberOfOrderDelivered:{
              type: Number, 
            }
          },
          settlementHistory: [
                {
                  type: Schema.Types.ObjectId,
                   ref: collections.SETTLEMENTS,  
                }
         ]

        },
        {
            timestamps: true,
        }
); 

deliveryAgentSchema.methods.setHash = async function (password: string): Promise<void> {
  try {
    this.password = await argon2.hash(password);
  } catch (error) {
    return Promise.reject(error);
  }
}  

deliveryAgentSchema.methods.verifyHash = async function (password: string): Promise<boolean> {
  try {
    return await argon2.verify(this.password, password);
  } catch (error) {
    return Promise.reject(error);
  }
}


const deliveryAgentModel = model<IDeliveryAgentDocument>(collections.DELIVERYAGENT, deliveryAgentSchema);


export { deliveryAgentModel };
