



scalar ObjectId
scalar Upload




type Mutation{

    addNotificationViewPersonId(input:addNotificationViewPersonIdInput!):addNotificationViewPersonIdResponse!
    addRemoveMarkNotification(input:addNotificationViewPersonIdInput!):addNotificationViewPersonIdResponse!
}


type Query {

      getAllNotification:[getAllNotificationResponse]!
}


type getAllNotificationResponse{
   
          _id:ObjectId
          message:String
          permissions:[String]
          orderId:String
          title:String
          productId:ObjectId
          type:String
          view:[
             viewType
          ]
          createdAt:Date,
          updatedAt:Date




      
}

type viewType{

    id:ObjectId
    remove:Boolean
}


input addNotificationViewPersonIdInput{

       
         notificationId:ObjectId
}


type addNotificationViewPersonIdResponse{

        status:Boolean,
        msg:String
}



schema {
  mutation: Mutation
  query: Query
}


