  scalar Upload
  scalar JSONObject
  scalar ObjectId



# Vendor company Mutations


  type Mutation {
    addVendorCompany(input: AddVendorCompanyInput!, images:[Upload], fileMap: JSONObject): AddVendorCompanyResponse!
    updateVendorCompany(input: UpdateVendorCompanyInput!, images:[Upload], fileMap: JSONObject): UpdateVendorCompanyResponse!
    updateVendorCompanyByAdmin (input: UpdateVendorCompanyByAdminInput!, crLicense:Upload, cooCertificate:Upload) : UpdateVendorCompanyByAdminResponse!
  }

  input UpdateVendorCompanyByAdminInput {
    _id: ObjectId!
    companyName: String
    companyType: String
    crNumber: String
    status: String
    remarks: [String!]
  }

   # Type

   type VendorCompany {
        _id: String
        vendorId: String
        companyName:String
        companyType: String
        crNumber: String
        status: String
        crLicense: ImageData
        cooCertificate: ImageData
        remarks: [String]
    }  

    type vendorCompanyRecordsWithKycData {
        vendorId: String
        _id: String
        fullName: String
        isKycCompleted: String
        companyName: String
        companyType: String
        status: String
        crNumber: String
    }


    # Input

    input AddVendorCompanyInput {
        companyName:String!
        companyType: String!
        crNumber: String!
    }   

    input UpdateVendorCompanyInput {
        companyName:String
        companyType: String
        crNumber: String
    } 


    # Output

    type AddVendorCompanyResponse {
        _id: String!
        message: String
    }  

    type UpdateVendorCompanyResponse {
        message: String
    }  

    type VendorCompanyDeleteRecordResponse {
      _id: String!
      message: String
    }

    type UpdateVendorCompanyByAdminResponse {
      message: String
    }


# Vendor company Queries

  type Query {
    getAllVendorCompanyRecordsByAdmin(input: VendorCompanyRecordsByAdminFilter): VendorCompanyRecordsByAdminResponse!
    getVendorCompanyRecordByAdmin(input: VendorCompanyIdInput!): VendorCompanyRecordResponse!
    getVendorCompanyRecord:GetVendorCompanyRecordResponse!
  }   

    # Input
   
  input VendorCompanyIdInput {
    _id: String!
  }

  input VendorCompanyRecordsByAdminFilter {
    page: Int
    size: Int
    status: String
  }

    # Output

    type ImageData {
    fileType: String
    fileURL: String
    mimeType: String
    originalName: String
  }    
  
  type VendorCompanyRecordResponse {
    record: VendorCompany!
    message: String
  }

  type VendorCompanyRecordsByAdminResponse {
    maxRecords: Int!
    records: [vendorCompanyRecordsWithKycData!]
    message: String
  }

  type VendorCompanyStatusUpdationResponse {
    _id: String
    message: String
  }

 type GetVendorCompanyRecordResponse {
  record: VendorCompany!
  message: String
 }
    


# Schema

schema {
    mutation: Mutation,
    query:Query
}

